-- =============================================
-- Author:		XX
-- Create date: 08/11/2023
-- Description:	
-- Change Control
--	
-- =============================================
create PROCEDURE [rpt].[zz_deprecated_spSelectADNOPProc] @GO_LIVE date, @STARTDATE date, @ENDDATE date
AS
BEGIN
SET NOCOUNT ON;

--DECLARE @STARTDATE AS DATE 
--DECLARE @ENDDATE AS DATE
--DECLARE @GO_LIVE AS DATE
 
--SET @STARTDATE =DATEADD(MONTH,-1,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)); 
--SET @ENDDATE = DATEADD(DAY,-1,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)); 
--SET @GO_LIVE = '4/29/2022';


select
	*
from (
SELECT DISTINCT
	--ISNULL(CMI.FACILITY_GROUP_ID,'') AS [Hospital Identifier] -- Not populated in Clarity for HPI
	case
		when loc.loc_id like '43004%' or loc.loc_id like '43005%' then 370203
		when loc.loc_id like '43006%' then 370192 
	end [Hospital Identifier]
	,ISNULL(Cast(PE.PAT_ENC_CSN_ID as varchar),'') AS [Encounter/Patient Identifier]
	,CASE WHEN ht.TX_TYPE_HA_C = 1 AND LEN(ht.HCPCS_CODE) = 5 THEN ht.HCPCS_CODE
		  WHEN ht.TX_TYPE_HA_C = 1 AND LEN(ht.CPT_CODE) = 5 THEN ht.CPT_CODE
		  WHEN ht.TX_TYPE_HA_C = 1 AND LEN(eap.PROC_CODE) = 5 THEN eap.PROC_CODE
	 END AS [CPT/HCPCS Code]
	,ISNULL(COALESCE(HT.PERFORMING_PROV_ID,HT.BILLING_PROV_ID),'') AS [Procedure Physician ID]
	,CAST(HT.SERVICE_DATE AS DATE) AS [Procedure Date]
FROM [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].HSP_ACCOUNT HA
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].HSP_TRANSACTIONS HT ON HT.PAT_ENC_CSN_ID = HA.PRIM_ENC_CSN_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PATIENT PAT ON PAT.PAT_ID = HA.PAT_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PATIENT_3 PAT3 ON PAT3.PAT_ID = HA.PAT_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PAT_ENC PE ON PE.PAT_ENC_CSN_ID = HA.PRIM_ENC_CSN_ID
--INNER JOIN (select distinct proc_id, cpt_code from [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CLARITY_EAP_OT where CODE_TYPE_C = 1) as eot on eot.PROC_ID = HT.PROC_ID
LEFT JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].CLARITY_EAP eap ON eap.PROC_ID = ht.PROC_ID
LEFT OUTER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CLARITY_LOC LOC ON LOC.LOC_ID = HA.LOC_ID
LEFT OUTER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CMS_MU_LOC CML ON CML.LOC_ID = LOC.LOC_ID
LEFT OUTER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CMS_MU_INFO CMI ON CMI.CMS_MU_ID = CML.CMS_MU_ID
WHERE HA.SERV_AREA_ID = '430' --HPI
AND PAT3.IS_TEST_PAT_YN = 'N'
AND PE.CONTACT_DATE >= @STARTDATE AND PE.CONTACT_DATE <= @ENDDATE
AND PE.CONTACT_DATE >= @GO_LIVE
--AND PE.APPT_STATUS_C IN ('2','6') --COMPLETED / ARRIVED -- not needed as all billed accounts should be completed. This statement was also excluding visits without appts.
AND HA.ACCT_BASECLS_HA_C <> 1 --Outpatient
AND HT.TX_TYPE_HA_C = 1 --charge

) s1
where [Hospital Identifier] is not null

END
GO
