-- =============================================
-- Author:		Riley Roberson
-- Create date: 11/30/2023
-- Description:	Piggybacking off of Zeke's ExportDailyCensusData sp to make a subscription SSRS report 
-- Change Control: 
--	
-- =============================================
CREATE PROCEDURE [rpt].[spDailyCensusDataReport] --@currentdate date
AS

BEGIN 
SET NOCOUNT ON;


IF OBJECT_ID(N'Tempdb..##TempCensus') IS NOT NULL
Drop TABLE ##TempCensus



SELECT 

HSP.PAT_ID PatientID, 
HSP.HSP_ACCOUNT_ID AccountID
, p.PAT_MRN_ID as PatientMRN
, HSP.HSP_ACCOUNT_NAME Patient
, HSP.ACCT_BASECLS_HA_C StatusCode
, CASE WHEN HSP.ACCT_CLASS_HA_C = 101 THEN 'Inpatient'
	   WHEN HSP.ACCT_CLASS_HA_C = 104 THEN 'Observation'
	   WHEN HSP.ACCT_CLASS_HA_C = 108 THEN 'Surgery Admit'
	   ELSE NULL END as PatientStatus -- zcHSP.NAME PatientStatus
, rm.ROOM_NAME as Room
, bd.BED_LABEL as Bed
, l.LocationName LocationName
, ADT.EFFECTIVE_TIME EffectiveTime
, ADT.EVENT_TYPE_C EventCode
, zcADT.NAME EventName
, DISCH.PAT_ID
, LC.NAME LevelofCare

INTO ##TempCensus

from [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].hsp_account HSP -- 1 is IP

LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].ZC_ACCT_BASECLS_HA zcHSP ON zcHSP.ACCT_BASECLS_HA_C = HSP.ACCT_BASECLS_HA_C
LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PAT_ENC PE ON PE.HSP_ACCOUNT_ID = HSP.HSP_ACCOUNT_ID
LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].[CLARITY_ADT] ADT ON ADT.PAT_ENC_CSN_ID = PE.PAT_ENC_CSN_ID
LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PAT_ENC_HSP PEH ON PEH.PAT_ENC_CSN_ID = ADT.PAT_ENC_CSN_ID
LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].[ZC_EVENT_TYPE] zcADT ON zcADT.EVENT_TYPE_C = ADT.EVENT_TYPE_C
LEFT JOIN [HPIDW].[dim].[vLocations] l ON HSP.ADM_LOC_ID = L.LocationSourceID
LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].ZC_ACCT_CLASS_HA zcACCT ON zcACCT.ACCT_CLASS_HA_C = HSP.ACCT_CLASS_HA_C
LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].[CLARITY_ADT] DISCH ON DISCH.PAT_ENC_CSN_ID = PE.PAT_ENC_CSN_ID AND DISCH.EVENT_TYPE_C = 2
LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].[ZC_LVL_OF_CARE] LC ON ADT.[PAT_LVL_OF_CARE_C] = LC.[LEVEL_OF_CARE_C]
LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].[PATIENT] p ON p.PAT_ID = HSP.PAT_ID
LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].[CLARITY_ROM] rm ON rm.ROOM_CSN_ID = adt.ROOM_CSN_ID 
LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].[CLARITY_BED] bd ON bd.BED_CSN_ID = adt.BED_CSN_ID

WHERE 1=1
AND ADT.EVENT_TIME > (GETDATE()-1) -- last day 
AND HSP.ACCT_CLASS_HA_C IN (101,104,108) -- 101 is IP, 104 is observation, 108 is surgery admit (per Tom)
AND DISCH.PAT_ID IS NULL -- self joined ADT discharges on pat ID and "discharged," if a record does not have an ID here, we keep them
AND ADT.EVENT_TYPE_C = 6 /*Midnight Census*/





SELECT * FROM ##TempCensus

--EXEC [rpt].[spDailyCensusDataReport]




END
GO
