-- =============================================
-- Author:		XX
-- Create date: 08/11/2023
-- Description:	
-- Change Control
--	
-- =============================================
create PROCEDURE [rpt].[zz_deprecated_spSelectADNPayerFile] @GO_LIVE date, @STARTDATE date, @ENDDATE date
AS
BEGIN
SET NOCOUNT ON;

--DECLARE @STARTDATE AS DATE 
--DECLARE @ENDDATE AS DATE
--DECLARE @GO_LIVE AS DATE
 
--SET @STARTDATE =DATEADD(MONTH,-1,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)); 
--SET @ENDDATE = DATEADD(DAY,-1,DATEFROMPARTS(YEAR(GETDATE()),MONTH(GETDATE()),1)); 
--SET @GO_LIVE = '4/29/2022';

DROP TABLE IF EXISTS #OP_TEMP;
DROP TABLE IF EXISTS #IP_TEMP;

SELECT 
--ISNULL(CMI.FACILITY_GROUP_ID,'') AS [Hospital Identifier] -- Not populated in Clarity for HPI
case
    when loc.loc_id like '43004%' or loc.loc_id like '43005%' then 370203
    when loc.loc_id like '43006%' then 370192 
end [Hospital Identifier]
,ISNULL(Cast(PE.PAT_ENC_CSN_ID as varchar),'') AS [Encounter/Patient Identifier/Billing ID]
,epm.PAYOR_ID AS [Payer/Insurance Code]
,case when fc.FINANCIAL_CLASS in (2,101,140,220,300,301,302,303,304,305,306) THEN 1 --Medicare
     when fc.FINANCIAL_CLASS in (3,215) THEN 2 --Medicaid
       when fc.FINANCIAL_CLASS in (5,240) THEN 3 --Worker's Comp
       when fc.FINANCIAL_CLASS = 6 THEN 4 --Tricare
       when fc.FINANCIAL_CLASS = 150 THEN 11 --Other HMO
       when fc.FINANCIAL_CLASS = 4 THEN 13 --Self Pay
       when fc.FINANCIAL_CLASS IS NULL THEN 13 --Self Pay
       else 10/*Other Commercial*/ end as [ADN Standard Payer Code]
,HAC.LINE AS [Payer Type]
--,'' AS [HIC Number]
INTO #OP_TEMP
FROM [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].HSP_ACCOUNT HA
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PATIENT PAT ON PAT.PAT_ID = HA.PAT_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PATIENT_3 PAT3 ON PAT3.PAT_ID = HA.PAT_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PAT_ENC PE ON PE.PAT_ENC_CSN_ID = HA.PRIM_ENC_CSN_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].HSP_ACCT_CVG_LIST HAC ON HAC.COVERAGE_ID = HA.COVERAGE_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].Coverage c on c.COVERAGE_ID = HAC.COVERAGE_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CLARITY_EPM EPM ON EPM.PAYOR_ID = C.PAYOR_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CLARITY_FC FC ON FC.FINANCIAL_CLASS = EPM.FINANCIAL_CLASS
LEFT OUTER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CLARITY_LOC LOC ON LOC.LOC_ID = HA.LOC_ID
LEFT OUTER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CMS_MU_LOC CML ON CML.LOC_ID = LOC.LOC_ID
LEFT OUTER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CMS_MU_INFO CMI ON CMI.CMS_MU_ID = CML.CMS_MU_ID
WHERE HA.SERV_AREA_ID = '430' --HPI
AND PAT3.IS_TEST_PAT_YN = 'N'
AND PE.CONTACT_DATE >= @STARTDATE AND PE.CONTACT_DATE <= @ENDDATE
AND PE.CONTACT_DATE >= @GO_LIVE
--AND PE.APPT_STATUS_C IN ('2','6') --COMPLETED / ARRIVED
AND HA.ACCT_BASECLS_HA_C <> 1


SELECT 
--ISNULL(CMI.FACILITY_GROUP_ID,'') AS [Hospital Identifier] -- Not populated in Clarity for HPI
case
    when loc.loc_id like '43004%' or loc.loc_id like '43005%' then 370203
    when loc.loc_id like '43006%' then 370192 
end [Hospital Identifier]
,ISNULL(Cast(PE.PAT_ENC_CSN_ID as varchar),'') AS [Encounter/Patient Identifier/Billing ID]
,epm.PAYOR_ID AS [Payer/Insurance Code]
,case when fc.FINANCIAL_CLASS in (2,101,140,220,300,301,302,303,304,305,306) THEN 1 --Medicare
     when fc.FINANCIAL_CLASS in (3,215) THEN 2 --Medicaid
       when fc.FINANCIAL_CLASS in (5,240) THEN 3 --Worker's Comp
       when fc.FINANCIAL_CLASS = 6 THEN 4 --Tricare
       when fc.FINANCIAL_CLASS = 150 THEN 11 --Other HMO
       when fc.FINANCIAL_CLASS = 4 THEN 13 --Self Pay
       when fc.FINANCIAL_CLASS IS NULL THEN 13 --Self Pay
       else 10/*Other Commercial*/ end as [ADN Standard Payer Code]
,HAC.LINE AS [Payer Type]
--,'' AS [HIC Number]
INTO #IP_TEMP
FROM [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].HSP_ACCOUNT HA
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PATIENT PAT ON PAT.PAT_ID = HA.PAT_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PATIENT_3 PAT3 ON PAT3.PAT_ID = HA.PAT_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].PAT_ENC PE ON PE.PAT_ENC_CSN_ID = HA.PRIM_ENC_CSN_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].HSP_ACCT_CVG_LIST HAC ON HAC.COVERAGE_ID = HA.COVERAGE_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].Coverage c on c.COVERAGE_ID = HAC.COVERAGE_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CLARITY_EPM EPM ON EPM.PAYOR_ID = C.PAYOR_ID
INNER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CLARITY_FC FC ON FC.FINANCIAL_CLASS = EPM.FINANCIAL_CLASS
LEFT OUTER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CLARITY_LOC LOC ON LOC.LOC_ID = HA.LOC_ID
LEFT OUTER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CMS_MU_LOC CML ON CML.LOC_ID = LOC.LOC_ID
LEFT OUTER JOIN [DBSQ_CLARITY.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].CMS_MU_INFO CMI ON CMI.CMS_MU_ID = CML.CMS_MU_ID
WHERE HA.SERV_AREA_ID = '430' --HPI
AND PAT3.IS_TEST_PAT_YN = 'N'
AND PAT.BIRTH_DATE IS NOT NULL
AND HA.DISCH_DATE_TIME >= @STARTDATE AND HA.DISCH_DATE_TIME <= @ENDDATE
AND HA.DISCH_DATE_TIME >= @GO_LIVE
AND HA.ACCT_BASECLS_HA_C = 1

select s1.*
from (
SELECT * FROM #IP_TEMP
UNION
SELECT * FROM #OP_TEMP
) s1 where [Hospital Identifier] is not null

END
GO
