CREATE procedure [rpt].[spSelectAJRRProcedures] as

-- run time for last 5 months: 10 min

DROP TABLE IF EXISTS #ALLPROC
DROP TABLE IF EXISTS #AllDX 
DROP TABLE IF EXISTS #AllDX2
DROP TABLE IF EXISTS #AllICD
DROP TABLE IF EXISTS #AllICD2
DROP TABLE IF EXISTS #ALLCC
DROP TABLE IF EXISTS #ALLPOA
DROP TABLE IF EXISTS #ANESTYPE
DROP TABLE IF EXISTS #ALLIMPLANTS
DROP TABLE IF EXISTS #IMPLANTINFO


DECLARE @START_DATE DATE =  DATEADD(MONTH,-5,CONVERT(DATE,GETDATE()))
DECLARE @END_DATE DATE = DATEADD(MONTH,1,CONVERT(DATE,GETDATE()))

/*Temp Table - #ALLPROC*/
	SELECT LOG_ID
      ,SURGERY_DATE
      ,ASA_RATE_C
      ,PAT_ID
      ,PRIMARY_PHYS_ID
      ,PAT_TYPE_C
      ,LOC_ID
      ,INPATIENT_DATA_ID
      ,SURGICAL_APPROACH
      ,LATERALITY
      ,[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18],[19],[20]
	INTO #ALLPROC
	FROM
	(
    -- Step 1: Get one row per LOG_ID + LINE with the CPT code and case-level attributes
		SELECT
		    ORPROC.LOG_ID
		    ,ORPROC.LINE
		    ,MIN(orplist.CPTCode) AS CPTCode          -- ensures lowest CPT wins if dupes slip through
		    ,MAX(ORL.SURGERY_DATE)      AS SURGERY_DATE
		    ,MAX(ORL2.ASA_RATE_C)       AS ASA_RATE_C
		    ,MAX(ORL.PAT_ID)            AS PAT_ID
		    ,MAX(ORL.PRIMARY_PHYS_ID)   AS PRIMARY_PHYS_ID
		    ,MAX(ORL.PAT_TYPE_C)        AS PAT_TYPE_C
		    ,MAX(ORL.LOC_ID)            AS LOC_ID
		    ,MAX(ORL.INPATIENT_DATA_ID) AS INPATIENT_DATA_ID
		    ,MAX(CASE 
		            WHEN ORPROC.ALL_APPROACH_C = 1 THEN '1'
		            WHEN ORPROC.ALL_APPROACH_C = 2 THEN '3'
		            WHEN ORPROC.ALL_APPROACH_C = 3 THEN '4'
		            WHEN ORPROC.ALL_APPROACH_C = 5 THEN '2' 
		            ELSE 'NR' 
		         END)                   AS SURGICAL_APPROACH
		    ,MAX(LAT.ABBR)              AS LATERALITY
		FROM [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_ALL_PROC ORPROC
		    INNER JOIN (
			    SELECT 
			        orproc.LOG_ID
			        ,orproc.LINE          -- this is OR_LOG_ALL_PROC.LINE (the procedure position)
			        ,cpt.REAL_CPT_CODE AS CPTCode
			    FROM [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_ALL_PROC orproc
			        INNER JOIN (
			            -- For each OR_PROC_ID, grab only the CPT row with the lowest LINE
						        SELECT 
						            c.OR_PROC_ID
						            ,c.REAL_CPT_CODE
						            ,ROW_NUMBER() OVER (PARTITION BY c.OR_PROC_ID ORDER BY c.LINE ASC) AS RN
						        FROM [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_PROC_CPT_ID c
						            INNER JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].GROUPER_RECORDS vcg 
						                ON vcg.GRP_REC_LIST_VALUE = c.CPT_ID 
						                AND vcg.GROUPER_ID = '122095'
						    ) cpt 
						        ON cpt.OR_PROC_ID = orproc.OR_PROC_ID 
						        AND cpt.RN = 1        -- ← only the first LINE of CPT codes for this procedure
						) orplist 
						    ON orplist.LOG_ID = ORPROC.LOG_ID 
						    AND orplist.LINE = ORPROC.LINE
				        
					INNER JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG ORL 
					    ON ORL.LOG_ID = ORPROC.LOG_ID
					INNER JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_2 ORL2 
					    ON ORL2.LOG_ID = ORPROC.LOG_ID
					LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].CLARITY_LOC LOC 
					    ON LOC.LOC_ID = ORL.LOC_ID
					LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].[ZC_OR_LRB] LAT 
					    ON LAT.LRB_C = ORPROC.LRB_C
		WHERE ORL.SURGERY_DATE BETWEEN @START_DATE AND @END_DATE
		    AND LOC.SERV_AREA_ID = 430
		GROUP BY
		    ORPROC.LOG_ID
		    ,ORPROC.LINE                              -- ← key: one row per LOG_ID/LINE before pivot
	) AS SOURCETABLE
	PIVOT
	(
	    MAX(CPTCode)
	    FOR LINE IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18],[19],[20])
	) AS PIVOTTABLE

/*Temp Table - #ALLDX*/ 
		SELECT 
			dx.HSP_ACCOUNT_ID
			,dx.LINE
			,dx.REF_BILL_CODE as ICD10Dx
			,CASE WHEN dx.DX_POA_NAME = 'Yes' THEN 'Y'
				  WHEN LEFT(dx.DX_POA_NAME,1) = 'E' THEN 'E'
				  WHEN LEFT(dx.DX_POA_NAME,1) = 'N' THEN 'N'
				  ELSE 'NR' END as POA
			,ISNULL(LEFT(dx.DX_COMORBIDITY_NAME,1),'NR') AS CC
			--,hsp.*
		INTO #ALLDX
		FROM [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].V_CODING_ALL_DX_PX_LIST dx
			LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].HSP_ACCOUNT HSP ON HSP.HSP_ACCOUNT_ID = dx.HSP_ACCOUNT_ID
		WHERE 1=1 
			AND dx.SOURCE_KEY IN (3 /*Final Diagnoses*/) 
			--AND (HSP.ADM_DATE_TIME BETWEEN @START_DATE AND @END_DATE 
			--	OR HSP.DISCH_DATE_TIME BETWEEN @START_DATE AND @END_DATE)
			--AND dx.HSP_ACCOUNT_ID = '605949715'
			
/*Temp Table - #ALLDX2*/
	SELECT HSP_ACCOUNT_ID 
			  ,[1],[2],[3],[4],[5],[6],[7],[8],[9],[10], [11], [12], [13], [14] ,[15] ,[16], [17], [18] ,[19] ,[20]
		INTO #ALLDX2	
	FROM  (
		SELECT 
			dx.HSP_ACCOUNT_ID
			,dx.LINE
			,dx.ICD10Dx
		FROM #ALLDX dx
		) SOURCETABLE
			PIVOT  
		(  
		MAX(ICD10Dx)
		FOR LINE IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10], [11], [12], [13], [14] ,[15] ,[16], [17], [18] ,[19] ,[20])
 
		) AS PIVOTTABLE 

/*Temp Table - #ALLICD*/ 
		SELECT 
			icd.HSP_ACCOUNT_ID
			,icd.LINE
			,icd.REF_BILL_CODE as ICD10Dx
			--,CASE WHEN dx.DX_POA_NAME = 'Yes' THEN 'Y'
			--	  WHEN LEFT(dx.DX_POA_NAME,1) = 'E' THEN 'E'
			--	  WHEN LEFT(dx.DX_POA_NAME,1) = 'N' THEN 'N'
			--	  ELSE 'NR' END as POA
			--,ISNULL(LEFT(dx.DX_COMORBIDITY_NAME,1),'NR') AS CC
			--,hsp.*
		INTO #ALLICD
		FROM [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[CLARITY].[ORGFILTER].V_CODING_ALL_DX_PX_LIST icd
			LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].HSP_ACCOUNT HSP ON HSP.HSP_ACCOUNT_ID = icd.HSP_ACCOUNT_ID
		WHERE 1=1 
			AND icd.SOURCE_KEY IN (11 /*ICD10 Codes*/) 
			AND (HSP.ADM_DATE_TIME BETWEEN @START_DATE AND @END_DATE 
				OR HSP.DISCH_DATE_TIME BETWEEN @START_DATE AND @END_DATE)
			--AND dx.HSP_ACCOUNT_ID = '605949715'
		
			
/*Temp Table - #ALLICD2*/
	SELECT HSP_ACCOUNT_ID 
			  ,[1],[2],[3],[4],[5],[6],[7],[8],[9],[10], [11], [12], [13], [14] ,[15] ,[16], [17], [18] ,[19] ,[20]
		INTO #ALLICD2	
	FROM  (
		SELECT 
			icd.HSP_ACCOUNT_ID
			,icd.LINE
			,icd.ICD10Dx
		FROM #ALLICD icd
		) SOURCETABLE
			PIVOT  
		(  
		MAX(ICD10Dx)
		FOR LINE IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10], [11], [12], [13], [14] ,[15] ,[16], [17], [18] ,[19] ,[20])
 
		) AS PIVOTTABLE 
/*Temp Table - #ALLPOA*/
	SELECT HSP_ACCOUNT_ID 
			  ,[1],[2],[3],[4],[5],[6],[7],[8],[9],[10], [11], [12], [13], [14] ,[15] ,[16], [17], [18] ,[19] ,[20]
		INTO #ALLPOA		
	FROM  (
		SELECT 
			dx.HSP_ACCOUNT_ID
			,dx.LINE
			,dx.POA
		FROM #ALLDX dx
		) SOURCETABLE
			PIVOT  
		(  
		MAX(POA)
		FOR LINE IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10], [11], [12], [13], [14] ,[15] ,[16], [17], [18] ,[19] ,[20])
 
		) AS PIVOTTABLE 
		
/*Temp Table - #ALLCC*/
	SELECT HSP_ACCOUNT_ID 
			  ,[1],[2],[3],[4],[5],[6],[7],[8],[9],[10], [11], [12], [13], [14] ,[15] ,[16], [17], [18] ,[19] ,[20]
		INTO #ALLCC		
	FROM  (
		SELECT 
			dx.HSP_ACCOUNT_ID
			,dx.LINE
			,dx.CC
		FROM #ALLDX dx
		) SOURCETABLE
			PIVOT  
		(  
		MAX(CC)
		FOR LINE IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10], [11], [12], [13], [14] ,[15] ,[16], [17], [18] ,[19] ,[20])
 
		) AS PIVOTTABLE 


/*Temp Table - #ALLIMPLANTS*/
	SELECT
	IMPLANT_LOG_ID
	,[1] AS IMPLANT_ID1
	,[2] AS IMPLANT_ID2
	,[3] AS IMPLANT_ID3
	,[4] AS IMPLANT_ID4
	,[5] AS IMPLANT_ID5
	,[6] AS IMPLANT_ID6
	,[7] AS IMPLANT_ID7
	,[8] AS IMPLANT_ID8
	,[9] AS IMPLANT_ID9
	,[10] AS IMPLANT_ID10
	,[11] AS IMPLANT_ID11
	,[12] AS IMPLANT_ID12
	,[13] AS IMPLANT_ID13
	,[14] AS IMPLANT_ID14
	,[15] AS IMPLANT_ID15
	,[16] AS IMPLANT_ID16
	,[17] AS IMPLANT_ID17
	,[18] AS IMPLANT_ID18
	,[19] AS IMPLANT_ID19
	,[20] AS IMPLANT_ID20
	INTO #ALLIMPLANTS
	FROM

	(SELECT 
		ROW_NUMBER() OVER(PARTITION BY ORIMP.IMPLANT_LOG_ID ORDER BY ORIMP.IMPLANT_LOG_ID DESC) AS LINE
		,ORIMP.IMPLANT_LOG_ID
		,ORIMP.IMPLANT_ID

	FROM [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP_IMPLANT ORIMP
		INNER JOIN #ALLPROC ON #ALLPROC.LOG_ID = ORIMP.IMPLANT_LOG_ID
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].CLARITY_LOC LOC ON LOC.LOC_ID = #ALLPROC.LOC_ID

	) AS SOURCETABLE
	PIVOT
	(MAX(IMPLANT_ID)
	FOR LINE IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18],[19],[20])) AS PIVOTTABLE

/*Temp Table - #IMPLANTINFO*/
	SELECT 
	#ALLIMPLANTS.IMPLANT_LOG_ID
	,IMP1.IMPLANT_NAME AS IMPLANT_NAME_1
	,IMP1.MODEL_NUMBER AS MODEL_NUMBER_1
	,IMP1.LOT_NUMBER AS LOT_NUMBER_1
	,MFG1.NAME AS MFG1
	,IMP2.IMPLANT_NAME AS IMPLANT_NAME_2
	,IMP2.MODEL_NUMBER AS MODEL_NUMBER_2
	,IMP2.LOT_NUMBER AS LOT_NUMBER_2
	,MFG2.NAME AS MFG2
	,IMP3.IMPLANT_NAME AS IMPLANT_NAME_3
	,IMP3.MODEL_NUMBER AS MODEL_NUMBER_3
	,IMP3.LOT_NUMBER AS LOT_NUMBER_3
	,MFG3.NAME AS MFG3
	,IMP4.IMPLANT_NAME AS IMPLANT_NAME_4
	,IMP4.MODEL_NUMBER AS MODEL_NUMBER_4
	,IMP4.LOT_NUMBER AS LOT_NUMBER_4
	,MFG4.NAME AS MFG4
	,IMP5.IMPLANT_NAME AS IMPLANT_NAME_5
	,IMP5.MODEL_NUMBER AS MODEL_NUMBER_5
	,IMP5.LOT_NUMBER AS LOT_NUMBER_5
	,MFG5.NAME AS MFG5
	,IMP6.IMPLANT_NAME AS IMPLANT_NAME_6
	,IMP6.MODEL_NUMBER AS MODEL_NUMBER_6
	,IMP6.LOT_NUMBER AS LOT_NUMBER_6
	,MFG6.NAME AS MFG6
	,IMP7.IMPLANT_NAME AS IMPLANT_NAME_7
	,IMP7.MODEL_NUMBER AS MODEL_NUMBER_7
	,IMP7.LOT_NUMBER AS LOT_NUMBER_7
	,MFG7.NAME AS MFG7
	,IMP8.IMPLANT_NAME AS IMPLANT_NAME_8
	,IMP8.MODEL_NUMBER AS MODEL_NUMBER_8
	,IMP8.LOT_NUMBER AS LOT_NUMBER_8
	,MFG8.NAME AS MFG8
	,IMP9.IMPLANT_NAME AS IMPLANT_NAME_9
	,IMP9.MODEL_NUMBER AS MODEL_NUMBER_9
	,IMP9.LOT_NUMBER AS LOT_NUMBER_9
	,MFG9.NAME AS MFG9
	,IMP10.IMPLANT_NAME AS IMPLANT_NAME_10
	,IMP10.MODEL_NUMBER AS MODEL_NUMBER_10
	,IMP10.LOT_NUMBER AS LOT_NUMBER_10
	,MFG10.NAME AS MFG10
	,IMP11.IMPLANT_NAME AS IMPLANT_NAME_11
	,IMP11.MODEL_NUMBER AS MODEL_NUMBER_11
	,IMP11.LOT_NUMBER AS LOT_NUMBER_11
	,MFG11.NAME AS MFG11
	,IMP12.IMPLANT_NAME AS IMPLANT_NAME_12
	,IMP12.MODEL_NUMBER AS MODEL_NUMBER_12
	,IMP12.LOT_NUMBER AS LOT_NUMBER_12
	,MFG12.NAME AS MFG12
	,IMP13.IMPLANT_NAME AS IMPLANT_NAME_13
	,IMP13.MODEL_NUMBER AS MODEL_NUMBER_13
	,IMP13.LOT_NUMBER AS LOT_NUMBER_13
	,MFG13.NAME AS MFG13
	,IMP14.IMPLANT_NAME AS IMPLANT_NAME_14
	,IMP14.MODEL_NUMBER AS MODEL_NUMBER_14
	,IMP14.LOT_NUMBER AS LOT_NUMBER_14
	,MFG14.NAME AS MFG14
	,IMP15.IMPLANT_NAME AS IMPLANT_NAME_15
	,IMP15.MODEL_NUMBER AS MODEL_NUMBER_15
	,IMP15.LOT_NUMBER AS LOT_NUMBER_15
	,MFG15.NAME AS MFG15
	,IMP16.IMPLANT_NAME AS IMPLANT_NAME_16
	,IMP16.MODEL_NUMBER AS MODEL_NUMBER_16
	,IMP16.LOT_NUMBER AS LOT_NUMBER_16
	,MFG16.NAME AS MFG16
	,IMP17.IMPLANT_NAME AS IMPLANT_NAME_17
	,IMP17.MODEL_NUMBER AS MODEL_NUMBER_17
	,IMP17.LOT_NUMBER AS LOT_NUMBER_17
	,MFG17.NAME AS MFG17
	,IMP18.IMPLANT_NAME AS IMPLANT_NAME_18
	,IMP18.MODEL_NUMBER AS MODEL_NUMBER_18
	,IMP18.LOT_NUMBER AS LOT_NUMBER_18
	,MFG18.NAME AS MFG18
	,IMP19.IMPLANT_NAME AS IMPLANT_NAME_19
	,IMP19.MODEL_NUMBER AS MODEL_NUMBER_19
	,IMP19.LOT_NUMBER AS LOT_NUMBER_19
	,MFG19.NAME AS MFG19
	,IMP20.IMPLANT_NAME AS IMPLANT_NAME_20
	,IMP20.MODEL_NUMBER AS MODEL_NUMBER_20
	,IMP20.LOT_NUMBER AS LOT_NUMBER_20
	,MFG20.NAME AS MFG20
	--,IMPLANT_ID1

	INTO #IMPLANTINFO

	FROM #ALLIMPLANTS
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].[OR_IMP] IMP1 ON IMP1.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID1
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG1 ON MFG1.INTERNAL_ID = IMP1.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP2 ON IMP2.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID2
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG2 ON MFG2.INTERNAL_ID = IMP2.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP3 ON IMP3.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID3
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG3 ON MFG3.INTERNAL_ID = IMP3.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP4 ON IMP4.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID4
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG4 ON MFG4.INTERNAL_ID = IMP4.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP5 ON IMP5.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID5
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG5 ON MFG5.INTERNAL_ID = IMP5.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP6 ON IMP6.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID6
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG6 ON MFG6.INTERNAL_ID = IMP6.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP7 ON IMP7.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID7
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG7 ON MFG7.INTERNAL_ID = IMP7.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP8 ON IMP8.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID8
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG8 ON MFG8.INTERNAL_ID = IMP8.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].[OR_IMP] IMP9 ON IMP9.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID9
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG9 ON MFG9.INTERNAL_ID = IMP9.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP10 ON IMP10.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID10
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG10 ON MFG10.INTERNAL_ID = IMP10.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP11 ON IMP11.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID11
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG11 ON MFG11.INTERNAL_ID = IMP11.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP12 ON IMP12.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID12
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG12 ON MFG12.INTERNAL_ID = IMP12.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP13 ON IMP13.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID13
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG13 ON MFG13.INTERNAL_ID = IMP13.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP14 ON IMP14.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID14
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG14 ON MFG14.INTERNAL_ID = IMP14.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP15 ON IMP15.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID15
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG15 ON MFG15.INTERNAL_ID = IMP15.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP16 ON IMP16.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID16
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG16 ON MFG16.INTERNAL_ID = IMP16.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP17 ON IMP17.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID17
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG17 ON MFG17.INTERNAL_ID = IMP17.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP18 ON IMP18.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID18
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG18 ON MFG18.INTERNAL_ID = IMP18.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP19 ON IMP19.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID19
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG19 ON MFG19.INTERNAL_ID = IMP19.MANUFACTURER_C
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_IMP IMP20 ON IMP20.IMPLANT_ID = #ALLIMPLANTS.IMPLANT_ID20
		LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_OR_MANUFACTURER MFG20 ON MFG20.INTERNAL_ID = IMP20.MANUFACTURER_C


/*Temp Table - #ANESTYPE*/
	SELECT 
	ANES.LOG_ID
	,CASE WHEN ANES.LOG_ANESTH_TYPE_C = 80 THEN '1' 
	 WHEN ANES.LOG_ANESTH_TYPE_C = 180 THEN '2'
	 WHEN ANES.LOG_ANESTH_TYPE_C = 40 THEN '5' ELSE NULL END AS 'ANESTYPE1'
	,CASE WHEN ANES2.LOG_ANESTH_TYPE_C = 80 THEN '1' 
	 WHEN ANES2.LOG_ANESTH_TYPE_C = 180 THEN '2'
	 WHEN ANES2.LOG_ANESTH_TYPE_C = 40 THEN '5' ELSE NULL END AS 'ANESTYPE2'

	INTO #ANESTYPE
	FROM [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_ANES_TYPES ANES
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_ANES_TYPES ANES2
	ON ANES2.LOG_ID = ANES.LOG_ID
	AND ANES2.LINE= 2
	WHERE ANES.LINE = 1

/*QUERY OUTPUT*/
	SELECT DISTINCT
	#ALLPROC.LOG_ID
	,LINK.OR_LINK_CSN
	,'AJRR'  AS 'REGISTRY'
	,'AJRR' AS 'MODULE'
	,'2021v1' AS 'VERSION'
	,'PROCEDURE' AS 'SubmissionType'
	, CLS.NAME AS 'RegistryAccountID'
	,'HPI COMMUNITY HOSPITAL' AS 'InstitutionName'
	,'NR' AS 'InstitutionNPI'--
	,LOC2.LOC_NAME AS 'Hospital_ASC_Name'
	,'HOSPNPI' AS 'Hospital_ASC_NPI'
	,PAT.PAT_MRN_ID AS 'PatInstitutionID'
	,PAT.SSN AS 'PatSSN'
	,pat.PAT_FIRST_NAME as'PatFirstName'
	,ISNULL(PAT.PAT_MIDDLE_NAME, 'NR') AS 'PatMiddleName'
	,PAT.PAT_LAST_NAME AS 'PatLastName'
	,PAT.BIRTH_DATE AS'PatDOB'
	,CASE WHEN PAT.DEATH_DATE IS NULL THEN  'NR' ELSE CONVERT(VARCHAR,PAT.DEATH_DATE, 101) END AS 'PatDeathDate'
	,SEX.NAME AS 'PatSex'
	,case when RACE.PATIENT_RACE_C = 3 then '1'--select * from [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_PATIENT_RACE
	when  race.PATIENT_RACE_C = 4 then '2'
	when  race.PATIENT_RACE_C = 2 then '3'
	when  race.PATIENT_RACE_C = 5 then '1'
	else 'NR' end AS 'PatRace'
	,case when pat.ETHNIC_GROUP_C = 2 then '1'
	when  pat.ETHNIC_GROUP_C= 1 then '2'
	else 'NR' end AS 'PatEthnicity' --select * from [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_ETHNIC_GROUP
	,PAT.CITY AS 'PatCity'
	,ST.NAME AS 'PatState'
	,PAT.ZIP AS 'PatZip'
	,COUNTRY.NAME AS 'PatCountry'
	,ISNULL(PAT.EMAIL_ADDRESS, 'NR') AS 'PatEmail'
	,SER.PROV_NAME AS 'surgeon name'
	,SER2.NPI AS 'SurNPI'
	,CONVERT(NUMERIC,vitals.LastHeight)*2.54 AS 'Pat_Height_cm'
	,CONVERT(NUMERIC, VITALS.LastWeight) * .02834952 AS 'Pat_Weight_kg'
	,'NR' AS 'Pat_Height_ftin'
	,CONVERT(NUMERIC, VITALS.LastWeight) / 16 AS 'Pat_Weight_lbs'
	,VITALS.LastBMI AS 'Pat_BMI'
	,'NR' AS 'Substance_Use_Screening'
	,CONVERT(DATE,#ALLPROC.SURGERY_DATE,101) AS 'ProcedureDate'
	,CONVERT(DATE,ENC.HOSP_ADMSN_TIME,101) AS 'ADMSNDT'
	,CONVERT(DATE,ENC.HOSP_DISCH_TIME,101)  AS 'DSCHRGDT'
	,ISNULL(ENC.DISCH_DISP_C ,'NR') AS 'DSCHDISPCODE'
	,ISNULL(CAST(#ALLPROC.[1]AS VARCHAR), 'NR') AS 'PROC_1'
	,ISNULL(CAST(#ALLPROC.[2]AS VARCHAR), 'NR') AS 'PROC_2'
	,ISNULL(CAST(#ALLPROC.[3]AS VARCHAR), 'NR') AS 'PROC_3'
	,ISNULL(CAST(#ALLPROC.[4]AS VARCHAR), 'NR') AS 'PROC_4'
	,ISNULL(CAST(#ALLPROC.[5]AS VARCHAR), 'NR') AS 'PROC_5'
	,ISNULL(CAST(#ALLPROC.[6]AS VARCHAR), 'NR') AS 'PROC_6'
	,ISNULL(CAST(#ALLPROC.[7]AS VARCHAR), 'NR') AS 'PROC_7'
	,ISNULL(CAST(#ALLPROC.[8]AS VARCHAR), 'NR') AS 'PROC_8'
	,ISNULL(CAST(#ALLPROC.[9]AS VARCHAR), 'NR') AS 'PROC_9'
	,ISNULL(CAST(#ALLPROC.[10]AS VARCHAR),'NR') AS 'PROC_10'
	,ISNULL(CAST(#ALLPROC.[11]AS VARCHAR), 'NR') AS 'PROC_11'
	,ISNULL(CAST(#ALLPROC.[12]AS VARCHAR), 'NR') AS 'PROC_12'
	,ISNULL(CAST(#ALLPROC.[13]AS VARCHAR), 'NR') AS 'PROC_13'
	,ISNULL(CAST(#ALLPROC.[14]AS VARCHAR), 'NR') AS 'PROC_14'
	,ISNULL(CAST(#ALLPROC.[15]AS VARCHAR), 'NR') AS 'PROC_15'
	,ISNULL(CAST(#ALLPROC.[16]AS VARCHAR), 'NR') AS 'PROC_16'
	,ISNULL(CAST(#ALLPROC.[17]AS VARCHAR), 'NR') AS 'PROC_17'
	,ISNULL(CAST(#ALLPROC.[18]AS VARCHAR), 'NR') AS 'PROC_18'
	,ISNULL(CAST(#ALLPROC.[19]AS VARCHAR), 'NR') AS 'PROC_19'
	,ISNULL(CAST(#ALLPROC.[20]AS VARCHAR),'NR') AS 'PROC_20'
	,ISNULL(CAST(#ALLICD2.[1]AS VARCHAR), 'NR') AS 'ICD10_1'
	,ISNULL(CAST(#ALLICD2.[2]AS VARCHAR), 'NR') AS 'ICD10_2'
	,ISNULL(CAST(#ALLICD2.[3]AS VARCHAR), 'NR') AS 'ICD10_3'
	,ISNULL(CAST(#ALLICD2.[4]AS VARCHAR), 'NR') AS 'ICD10_4'
	,ISNULL(CAST(#ALLICD2.[5]AS VARCHAR), 'NR') AS 'ICD10_5'
	,ISNULL(CAST(#ALLICD2.[6]AS VARCHAR), 'NR') AS 'ICD10_6'
	,ISNULL(CAST(#ALLICD2.[7]AS VARCHAR), 'NR') AS 'ICD10_7'
	,ISNULL(CAST(#ALLICD2.[8]AS VARCHAR), 'NR') AS 'ICD10_8'
	,ISNULL(CAST(#ALLICD2.[9]AS VARCHAR), 'NR') AS 'ICD10_9'
	,ISNULL(CAST(#ALLICD2.[10]AS VARCHAR), 'NR') AS 'ICD10_110'
	,ISNULL(CAST(#ALLICD2.[11]AS VARCHAR), 'NR') AS 'ICD10_11'
	,ISNULL(CAST(#ALLICD2.[12]AS VARCHAR), 'NR') AS 'ICD10_12'
	,ISNULL(CAST(#ALLICD2.[13]AS VARCHAR), 'NR') AS 'ICD10_13'
	,ISNULL(CAST(#ALLICD2.[14]AS VARCHAR), 'NR') AS 'ICD10_14'
	,ISNULL(CAST(#ALLICD2.[15]AS VARCHAR), 'NR') AS 'ICD10_15'
	,ISNULL(CAST(#ALLICD2.[16]AS VARCHAR), 'NR') AS 'ICD10_16'
	,ISNULL(CAST(#ALLICD2.[17]AS VARCHAR), 'NR') AS 'ICD10_17'
	,ISNULL(CAST(#ALLICD2.[18]AS VARCHAR), 'NR') AS 'ICD10_18'
	,ISNULL(CAST(#ALLICD2.[19]AS VARCHAR), 'NR') AS 'ICD10_19'
	,ISNULL(CAST(#ALLICD2.[20]AS VARCHAR), 'NR') AS 'ICD10_20'
	,ISNULL(CAST(#ALLICD2.[1]AS VARCHAR), 'NR') AS 'DX_1'
	,ISNULL(CAST(#ALLDX2.[2]AS VARCHAR), 'NR') AS 'DX_2'
	,ISNULL(CAST(#ALLDX2.[3]AS VARCHAR), 'NR') AS 'DX_3'
	,ISNULL(CAST(#ALLDX2.[4]AS VARCHAR), 'NR') AS 'DX_4'
	,ISNULL(CAST(#ALLDX2.[5]AS VARCHAR), 'NR') AS 'DX_5'
	,ISNULL(CAST(#ALLDX2.[6]AS VARCHAR), 'NR') AS 'DX_6'
	,ISNULL(CAST(#ALLDX2.[7]AS VARCHAR), 'NR') AS 'DX_7'
	,ISNULL(CAST(#ALLDX2.[8]AS VARCHAR), 'NR') AS 'DX_8'
	,ISNULL(CAST(#ALLDX2.[9]AS VARCHAR), 'NR') AS 'DX_9'
	,ISNULL(CAST(#ALLDX2.[10]AS VARCHAR), 'NR') AS 'DX_110'
	,ISNULL(CAST(#ALLDX2.[11]AS VARCHAR), 'NR') AS 'DX_11'
	,ISNULL(CAST(#ALLDX2.[12]AS VARCHAR), 'NR') AS 'DX_12'
	,ISNULL(CAST(#ALLDX2.[13]AS VARCHAR), 'NR') AS 'DX_13'
	,ISNULL(CAST(#ALLDX2.[14]AS VARCHAR), 'NR') AS 'DX_14'
	,ISNULL(CAST(#ALLDX2.[15]AS VARCHAR), 'NR') AS 'DX_15'
	,ISNULL(CAST(#ALLDX2.[16]AS VARCHAR), 'NR') AS 'DX_16'
	,ISNULL(CAST(#ALLDX2.[17]AS VARCHAR), 'NR') AS 'DX_17'
	,ISNULL(CAST(#ALLDX2.[18]AS VARCHAR), 'NR') AS 'DX_18'
	,ISNULL(CAST(#ALLDX2.[19]AS VARCHAR), 'NR') AS 'DX_19'
	,ISNULL(CAST(#ALLDX2.[20]AS VARCHAR), 'NR') AS 'DX_20'
	,#ALLPROC.LATERALITY AS 'DXLat'
	,#ALLPROC.Surgical_Approach AS 'SurgicalApproachHip'
	,#ALLPROC.Surgical_Approach AS 'SurgicalApproachKnee'
	,#ALLPROC.Surgical_Approach AS 'SurgicalApproachOther'
	,ISNULL(CAST(tech.TECHNIQUE_C AS VARCHAR), 'NR') AS 'SurgicalTechniqueHip'
	,ISNULL(CAST(tech.TECHNIQUE_C AS VARCHAR), 'NR') AS 'SurgicalTechniqueKnee'
	,orstart.TIMING_EVENT_DTTM AS 'OREntryTime'
	,orend.TIMING_EVENT_DTTM AS 'ORExitTime'
	--,orinc.TIMING_EVENT_DTTM AS 'IncisionStartTime'
	,ISNULL(CAST(orinc.TIMING_EVENT_DTTM AS VARCHAR), 'NR') AS 'IncisionStartTime'
	,ISNULL(CAST(orclose.TIMING_EVENT_DTTM AS VARCHAR), 'NR') AS 'SkinClosureTime'
	,case when tourn.TOURNIQUETS_ID is not null then 1 else 2 end AS 'TourniquetUse'
	, 'NR' AS 'ComputerNavigation'
	,case when robot.OR_CASE_ID is null then 2 else 1 end 'RoboticAssistedSurgery'
	,'NR'AS 'RoboticSystemName'
	,'NR'AS 'RoboticSoftwareVersion'
	,'NR'AS 'LengthofStay'
	,case when #anestype.Anestype2 is null then #anestype.Anestype1 else concat(#anestype.Anestype1,',',#anestype.Anestype2) end AS 'AnesthesiaType'
	,'NR'AS 'PeriarticularInjection'
	,ISNULL(#IMPLANTINFO.MFG1, 'NR') AS 'Mfg_1'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_1, 'NR') 'ComponentName_1'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_1, 'NR') AS 'Cat_1'
	,ISNULL(#IMPLANTINFO.LOT_NUMBER_1, 'NR') AS 'Lot_1'
	,ISNULL(#IMPLANTINFO.MFG2, 'NR') AS 'Mfg_2'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_2, 'NR')AS 'ComponentName_2'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_2, 'NR') AS 'Cat_2'
	,ISNULL(#IMPLANTINFO.LOT_NUMBER_2, 'NR') AS 'Lot_2'
	,ISNULL(#IMPLANTINFO.MFG3, 'NR') AS 'Mfg_3'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_3, 'NR') AS 'ComponentName_3'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_3, 'NR') AS 'Cat_3'
	,ISNULL(#IMPLANTINFO.LOT_NUMBER_3, 'NR') AS 'Lot_3'
	,ISNULL(#IMPLANTINFO.MFG4, 'NR') AS 'Mfg_4'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_4, 'NR')AS 'ComponentName_4'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_4, 'NR') AS 'Cat_4'
	,ISNULL(#IMPLANTINFO.LOT_NUMBER_4, 'NR') AS 'Lot_4'
	,ISNULL(#IMPLANTINFO.MFG5, 'NR') AS 'Mfg_5'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_5, 'NR')AS 'ComponentName_5'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_5, 'NR') AS 'Cat_5'
	,ISNULL(#IMPLANTINFO.LOT_NUMBER_5, 'NR') AS 'Lot_5'
	,ISNULL(#IMPLANTINFO.MFG6, 'NR') AS 'Mfg_6'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_6, 'NR')AS 'ComponentName_6'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_6, 'NR') AS 'Cat_6'
	,ISNULL(#IMPLANTINFO.LOT_NUMBER_6, 'NR') AS 'Lot_6'
	,ISNULL(#IMPLANTINFO.MFG7, 'NR') AS 'Mfg_7'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_7, 'NR') AS 'ComponentName_7'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_7, 'NR') AS 'Cat_7'
	,ISNULL(#IMPLANTINFO.LOT_NUMBER_7, 'NR') AS 'Lot_7'
	,ISNULL(#IMPLANTINFO.MFG8, 'NR') AS 'Mfg_8'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_8, 'NR') AS 'ComponentName_8'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_8, 'NR') AS 'Cat_8'
	,ISNULL(#IMPLANTINFO.LOT_NUMBER_8, 'NR') AS 'Lot_8'
	,ISNULL(#IMPLANTINFO.MFG9, 'NR') AS 'Mfg_9'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_9, 'NR')AS 'ComponentName_9'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_9, 'NR') AS 'Cat_9'
	,ISNULL(#IMPLANTINFO.LOT_NUMBER_9, 'NR') AS 'Lot_9'
	,ISNULL(#IMPLANTINFO.MFG10, 'NR') AS 'Mfg_10'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_10, 'NR')AS 'ComponentName_10'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_10, 'NR') AS 'Cat_10'
	,ISNULL(#IMPLANTINFO.LOT_NUMBER_10, 'NR') AS 'Lot_10'
	,ISNULL(#IMPLANTINFO.MFG11, 'NR') AS 'Mfg_11'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_11, 'NR')AS 'ComponentName_11'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_11, 'NR') AS 'Cat_11'
	,ISNULL(LOT_NUMBER_11, 'NR') AS 'Lot_11'
	,ISNULL(#IMPLANTINFO.MFG12, 'NR') AS 'Mfg_12'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_12, 'NR')AS 'ComponentName_12'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_12, 'NR') AS 'Cat_12'
	,ISNULL(LOT_NUMBER_12, 'NR') AS 'Lot_12'
	,ISNULL(#IMPLANTINFO.MFG13, 'NR') AS 'Mfg_13'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_13, 'NR')AS 'ComponentName_13'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_13, 'NR') AS 'Cat_13'
	,ISNULL(LOT_NUMBER_13, 'NR') AS 'Lot_13'
	,ISNULL(#IMPLANTINFO.MFG14, 'NR') AS 'Mfg_14'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_14, 'NR')AS 'ComponentName_14'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_14, 'NR') AS 'Cat_14'
	,ISNULL(LOT_NUMBER_14, 'NR') AS 'Lot_14'
	,ISNULL(#IMPLANTINFO.MFG15, 'NR') AS 'Mfg_15'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_15, 'NR')AS 'ComponentName_15'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_15, 'NR') AS 'Cat_15'
	,ISNULL(LOT_NUMBER_15, 'NR') AS 'Lot_15'
	,ISNULL(#IMPLANTINFO.MFG16, 'NR') AS 'Mfg_16'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_16, 'NR') AS 'ComponentName_16'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_16, 'NR') AS 'Cat_16'
	,ISNULL(LOT_NUMBER_16, 'NR') AS 'Lot_16'
	,ISNULL(#IMPLANTINFO.MFG17, 'NR') AS 'Mfg_17'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_17, 'NR')AS 'ComponentName_17'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_17, 'NR') AS 'Cat_17'
	,ISNULL(LOT_NUMBER_17, 'NR') AS 'Lot_17'
	,ISNULL(#IMPLANTINFO.MFG18, 'NR') AS 'Mfg_18'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_18, 'NR') AS 'ComponentName_18'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_18, 'NR') AS 'Cat_18'
	,ISNULL(LOT_NUMBER_18, 'NR') AS 'Lot_18'
	,ISNULL(#IMPLANTINFO.MFG19, 'NR') AS 'Mfg_19'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_19, 'NR')AS 'ComponentName_19'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_19, 'NR') AS 'Cat_19'
	,ISNULL(LOT_NUMBER_19, 'NR') AS 'Lot_19'
	,ISNULL(#IMPLANTINFO.MFG20, 'NR') AS 'Mfg_20'
	,ISNULL(#IMPLANTINFO.IMPLANT_NAME_20, 'NR')AS 'ComponentName_20'
	,ISNULL(#IMPLANTINFO.MODEL_NUMBER_20, 'NR') AS 'Cat_20'
	,ISNULL(LOT_NUMBER_20, 'NR') AS 'Lot_20'
	,#ALLPROC.asa_rate_c AS 'ASA_Class'
	,ISNULL(CAST(#ALLCC.[1]AS VARCHAR), 'NR') AS 'CoM_1'
	,ISNULL(CAST(#ALLCC.[2]AS VARCHAR), 'NR') AS 'CoM_2'
	,ISNULL(CAST(#ALLCC.[3]AS VARCHAR), 'NR') AS 'CoM_3'
	,ISNULL(CAST(#ALLCC.[4]AS VARCHAR), 'NR') AS 'CoM_4'
	,ISNULL(CAST(#ALLCC.[5]AS VARCHAR), 'NR') AS 'CoM_5'
	,ISNULL(CAST(#ALLCC.[6]AS VARCHAR), 'NR') AS 'CoM_6'
	,ISNULL(CAST(#ALLCC.[7]AS VARCHAR), 'NR') AS 'CoM_7'
	,ISNULL(CAST(#ALLCC.[8]AS VARCHAR), 'NR') AS 'CoM_8'
	,ISNULL(CAST(#ALLCC.[9]AS VARCHAR), 'NR') AS 'CoM_9'
	,ISNULL(CAST(#ALLCC.[10]AS VARCHAR), 'NR') AS 'CoM_10'
	,ISNULL(CAST(#ALLCC.[11]AS VARCHAR), 'NR') AS 'CoM_11'
	,ISNULL(CAST(#ALLCC.[12]AS VARCHAR), 'NR') AS 'CoM_12'
	,ISNULL(CAST(#ALLCC.[13]AS VARCHAR), 'NR') AS 'CoM_13'
	,ISNULL(CAST(#ALLCC.[14]AS VARCHAR), 'NR') AS 'CoM_14'
	,ISNULL(CAST(#ALLCC.[15]AS VARCHAR), 'NR') AS 'CoM_15'
	,ISNULL(CAST(#ALLCC.[16]AS VARCHAR), 'NR') AS 'CoM_16'
	,ISNULL(CAST(#ALLCC.[17]AS VARCHAR), 'NR') AS 'CoM_17'
	,ISNULL(CAST(#ALLCC.[18]AS VARCHAR), 'NR') AS 'CoM_18'
	,ISNULL(CAST(#ALLCC.[19]AS VARCHAR), 'NR') AS 'CoM_19'
	,ISNULL(CAST(#ALLCC.[20]AS VARCHAR), 'NR') AS 'CoM_20'
	,ISNULL(CAST(#ALLPOA.[1]AS VARCHAR), 'NR')AS 'POA_1'
	,ISNULL(CAST(#ALLPOA.[2]AS VARCHAR), 'NR')AS 'POA_2'
	,ISNULL(CAST(#ALLPOA.[3]AS VARCHAR), 'NR')AS 'POA_3'
	,ISNULL(CAST(#ALLPOA.[4]AS VARCHAR), 'NR')AS 'POA_4'
	,ISNULL(CAST(#ALLPOA.[5]AS VARCHAR), 'NR')AS 'POA_5'
	,ISNULL(CAST(#ALLPOA.[6]AS VARCHAR), 'NR')AS 'POA_6'
	,ISNULL(CAST(#ALLPOA.[7]AS VARCHAR), 'NR')AS 'POA_7'
	,ISNULL(CAST(#ALLPOA.[8]AS VARCHAR), 'NR')AS 'POA_8'
	,ISNULL(CAST(#ALLPOA.[9]AS VARCHAR), 'NR')AS 'POA_9'
	,ISNULL(CAST(#ALLPOA.[10]AS VARCHAR), 'NR')AS 'POA_10'
	,ISNULL(CAST(#ALLPOA.[11]AS VARCHAR), 'NR')AS 'POA_11'
	,ISNULL(CAST(#ALLPOA.[12]AS VARCHAR), 'NR')AS 'POA_12'
	,ISNULL(CAST(#ALLPOA.[13]AS VARCHAR), 'NR')AS 'POA_13'
	,ISNULL(CAST(#ALLPOA.[14]AS VARCHAR), 'NR')AS 'POA_14'
	,ISNULL(CAST(#ALLPOA.[15]AS VARCHAR), 'NR')AS 'POA_15'
	,ISNULL(CAST(#ALLPOA.[16]AS VARCHAR), 'NR')AS 'POA_16'
	,ISNULL(CAST(#ALLPOA.[17]AS VARCHAR), 'NR')AS 'POA_17'
	,ISNULL(CAST(#ALLPOA.[18]AS VARCHAR), 'NR')AS 'POA_18'
	,ISNULL(CAST(#ALLPOA.[19]AS VARCHAR), 'NR')AS 'POA_19'
	,ISNULL(CAST(#ALLPOA.[20]AS VARCHAR), 'NR')AS 'POA_20'
	--,'NR' AS 'CoM_11'
	--,'NR' AS 'POA_11'
	--,'NR' AS 'CoM_12'
	--,'NR' AS 'POA_12'
	--,'NR' AS 'CoM_13'
	--,'NR' AS 'POA_13'
	--,'NR' AS 'CoM_14'
	--,'NR' AS 'POA_14'
	--,'NR' AS 'CoM_15'
	--,'NR' AS 'POA_15'
	--,'NR' AS 'CoM_16'
	--,'NR' AS 'POA_16'
	--,'NR' AS 'CoM_17'
	--,'NR'AS 'POA_17'
	--,'NR'  AS 'CoM_18'
	--,'NR' AS 'POA_18'
	--,'NR' AS 'CoM_19'
	--,'NR' AS 'POA_19'
	--,'NR' AS 'CoM_20'
	--,'NR' AS 'POA_20'
	--,'NR' AS 'Trainee'
	--,ISNULL(#ALLCSNDX.PAYOR_NAME, 'NR') AS 'Payer_Status'
	--,'NR' AS 'Charlson_Index'
	--,'NR'AS 'TJC_AnesthesiaType'
	--,'NR' AS 'TJC_Rgnl_Ansth_Exemption'
	--,'NR' AS 'TJC_Ambulation'
	--,'NR' AS 'TJC_DSCHDISPCODE'
	--,'NR' AS 'TJC_Discharge_Exclusion'
	--,'NR' AS 'TJC_Admit_Source'
	--,'NR' AS 'Blood_Transfusion'
	--,'NR' AS 'Blood_Transfusion_Amount'
	--,'NR' AS 'Tranexamic_Acid_Usage'
	--,'NR' AS 'PT_Day_0'
	--,'NR' AS 'VTE_Prophylaxis'
	--,'NR' AS 'Perioperative_Antibiotics'
	--,'NR' AS 'Pain_Management'



	FROM  #ALLPROC 
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].PATIENT PAT	ON PAT.PAT_ID = #ALLPROC.PAT_ID
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].CLARITY_SER SER	ON SER.PROV_ID = #ALLPROC.PRIMARY_PHYS_ID
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].CLARITY_SER_2 SER2 ON SER2.PROV_ID = SER.PROV_ID
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_PAT_CLASS CLS ON CLS.INTERNAL_ID = #ALLPROC.PAT_TYPE_C
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_STATE ST	ON ST.INTERNAL_ID = PAT.STATE_C
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_COUNTRY COUNTRY ON COUNTRY.INTERNAL_ID = PAT.COUNTRY_C
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].ZC_SEX SEX ON SEX.INTERNAL_ID = PAT.SEX_C
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].PATIENT_RACE RACE ON RACE.PAT_ID = PAT.PAT_ID
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].PAT_OR_ADM_LINK LINK ON LINK.LOG_ID = #ALLPROC.LOG_ID
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].PAT_ENC_HSP ENC	ON ENC.PAT_ENC_CSN_ID = LINK.OR_LINK_CSN
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOC LOC ON LOC.LOC_ID = #ALLPROC.LOC_ID
	INNER JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].CLARITY_DEP DEP ON DEP.DEPARTMENT_ID = LOC.OR_DEPARTMENT_ID
																								AND DEP.SERV_AREA_ID = 430
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].CLARITY_LOC LOC2 ON LOC2.LOC_ID = DEP.REV_LOC_ID
	LEFT JOIN #ALLICD2 ON #ALLICD2.HSP_ACCOUNT_ID = ENC.HSP_ACCOUNT_ID
	LEFT JOIN #ALLDX2 ON #ALLDX2.HSP_ACCOUNT_ID = ENC.HSP_ACCOUNT_ID
	LEFT JOIN #ALLPOA ON #ALLPOA.HSP_ACCOUNT_ID = ENC.HSP_ACCOUNT_ID
	LEFT JOIN #ALLCC ON #ALLCC.HSP_ACCOUNT_ID = ENC.HSP_ACCOUNT_ID
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_TECHNIQUE TECH ON TECH.LOG_ID = #ALLPROC.LOG_ID
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_TIMING_EVENTS ORSTART ON ORSTART.LOG_ID = #ALLPROC.LOG_ID
																										  AND ORSTART.TIMING_EVENT_C = 700
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_TIMING_EVENTS OREND ON OREND.LOG_ID = #ALLPROC.LOG_ID
																										  AND OREND.TIMING_EVENT_C = 1200
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_TIMING_EVENTS ORINC ON ORINC.LOG_ID = #ALLPROC.LOG_ID
																										  AND ORINC.TIMING_EVENT_C = 1000
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_TIMING_EVENTS ORCLOSE ON ORCLOSE.LOG_ID = #ALLPROC.LOG_ID
																										  AND ORCLOSE.TIMING_EVENT_C = 1100
	LEFT JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_LOG_LN_TOURN TOURN ON TOURN.LOG_ID = #ALLPROC.LOG_ID
	LEFT JOIN #ANESTYPE	ON #ANESTYPE.LOG_ID = #ALLPROC.LOG_ID
	LEFT JOIN #IMPLANTINFO ON #IMPLANTINFO.IMPLANT_LOG_ID =#ALLPROC.LOG_ID
	LEFT JOIN(
		SELECT
			OR_CASE_ID
		FROM [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].OR_CASE_EQUIP_NEED EQUIP
		WHERE EQUIP.EQUIPMENT_TYPE_C IN (661,1185) --ROBOTIC TYPE
		GROUP BY OR_CASE_ID) ROBOT ON ROBOT.OR_CASE_ID = #ALLPROC.LOG_ID
	OUTER APPLY(
		SELECT
			FR2.FSD_ID
			,FR2.INPATIENT_DATA_ID
			,MEA.RECORDED_TIME
			,MEA.FLT_ID
			,FIRST_VALUE(CASE WHEN FLO_MEAS_ID = '11' THEN MEAS_VALUE ELSE NULL END) OVER (ORDER BY CASE WHEN FLO_MEAS_ID = '11' THEN 0 ELSE 1 END, CASE WHEN MEAS_VALUE IS NULL THEN 1 ELSE 0 END, RECORDED_TIME DESC ) AS 'LASTHEIGHT'  ---- WEIGHT
			,FIRST_VALUE(CASE WHEN FLO_MEAS_ID = '14' THEN MEAS_VALUE ELSE NULL END) OVER (ORDER BY CASE WHEN FLO_MEAS_ID = '14' THEN 0 ELSE 1 END, CASE WHEN MEAS_VALUE IS NULL THEN 1 ELSE 0 END, RECORDED_TIME DESC ) AS 'LASTWEIGHT'  ---- WEIGHT
			,FIRST_VALUE(CASE WHEN FLO_MEAS_ID = '301070' THEN MEAS_VALUE ELSE NULL END) OVER (ORDER BY CASE WHEN FLO_MEAS_ID = '301070' THEN 0 ELSE 1 END, CASE WHEN MEAS_VALUE IS NULL THEN 1 ELSE 0 END, RECORDED_TIME DESC ) AS 'LASTBMI'  ---- BMI
		FROM [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].IP_FLWSHT_REC FR2
			INNER JOIN [CLARITYRDBMS.CORP.INTEGRIS-HEALTH.COM].[Clarity].[ORGFILTER].IP_FLWSHT_MEAS MEA  ON MEA.FSD_ID = FR2.FSD_ID
		WHERE FR2.INPATIENT_DATA_ID = #ALLPROC.INPATIENT_DATA_ID
			AND FLO_MEAS_ID IS NOT NULL
			AND FLO_MEAS_ID IN ( '11', '14', '301070')
		ORDER BY MEA.RECORDED_TIME
		OFFSET 0 ROWS FETCH FIRST 1 ROWS ONLY) VITALS

DROP TABLE IF EXISTS #ALLPROC
DROP TABLE IF EXISTS #AllDX
DROP TABLE IF EXISTS #AllDX2  
DROP TABLE IF EXISTS #AllICD
DROP TABLE IF EXISTS #AllICD2
DROP TABLE IF EXISTS #ALLCC
DROP TABLE IF EXISTS #ALLPOA
DROP TABLE IF EXISTS #ANESTYPE
DROP TABLE IF EXISTS #ALLIMPLANTS
DROP TABLE IF EXISTS #IMPLANTINFO
GO
