CREATE TABLE [app].[PracticeProviderLookup] (
    [PracticeProviderID] INT NOT NULL,
    [PracticeID] VARCHAR(100) NOT NULL,
    [PracticeName] VARCHAR(100) NULL,
    [ProviderID] VARCHAR(100) NOT NULL,
    [ProviderDataSourceID] INT NULL,
    [ParentProviderID] VARCHAR(100) NULL,
    [ProviderFullName] VARCHAR(253) NULL,
    [ProviderFirstName] VARCHAR(100) NULL,
    [ProviderMiddleInitial] VARCHAR(50) NULL,
    [ProviderLastName] VARCHAR(100) NULL,
    [ProviderAbbreviation] VARCHAR(100) NULL,
    [PracticeProviderIsPrimary] BIT NULL,
    [PracticeProviderIsDefault] BIT NULL,
    [PracticeProviderEffectiveDate] DATE NULL,
    [PracticeProviderEndDate] DATE NULL,
    [PracticeProviderIsActive] BIT NULL,
    [PracticeProviderUpdatedDatetime] DATETIME NULL,
    [PracticeProviderFTE] DECIMAL(18,2) NULL,
    [PracticeProviderAllocationPercent] DECIMAL(18,8) NULL,
    [PracticeProviderLocation] VARCHAR(50) NULL,
    [PracticeProviderIsSpecialist] BIT NULL,
    [PracticeProviderIsMidLevel] BIT NULL,
    [PracticeProviderGLType] VARCHAR(30) NULL,
    [PracticeProviderGLTypeID] VARCHAR(30) NULL,
    [PracticeProviderGLProviderID] VARCHAR(10) NULL,
    [PracticeProviderDHSType] INT NULL
);
GO
