CREATE TABLE [dbo].[HCPCS] (
    [HCPCSID] INT IDENTITY(1,1) NOT NULL,
    [HCPCSProcedureCode] VARCHAR(50) NOT NULL,
    [HCPCSDescription] VARCHAR(200) NOT NULL,
    CONSTRAINT [PK_HCPCS] PRIMARY KEY ([HCPCSID])
);
GO
