CREATE TABLE [dim].[Patients] (
    [PatientID] VARCHAR(50) NOT NULL,
    [PatientDataSourceID] INT NULL,
    [PatientSourceID] VARCHAR(50) NULL,
    [PatientMRN] VARCHAR(50) NULL,
    [PatientFirstName] VARCHAR(100) NULL,
    [PatientMiddleInitial] VARCHAR(10) NULL,
    [PatientLastName] VARCHAR(100) NULL,
    [PatientFullName] VARCHAR(100) NULL,
    [PatientGender] VARCHAR(10) NULL,
    [PatientDateOfBirth] DATETIME NULL,
    [PatientSSN] VARCHAR(50) NULL,
    [PatientHomePhone] NVARCHAR(30) NULL,
    [PatientWorkPhone] NVARCHAR(30) NULL,
    [PatientWorkPhoneExtension] VARCHAR(50) NULL,
    [PatientMobilePhone] VARCHAR(30) NULL,
    [PatientEmailAddress] VARCHAR(100) NULL,
    [PatientStreetAddress1] VARCHAR(50) NULL,
    [PatientStreetAddress2] VARCHAR(50) NULL,
    [PatientCity] VARCHAR(50) NULL,
    [PatientState] VARCHAR(50) NULL,
    [PatientZipCode] VARCHAR(50) NULL,
    [PatientMaritalStatus] VARCHAR(50) NULL,
    [PatientEthnicity] VARCHAR(50) NULL,
    [PatientLanguage] VARCHAR(50) NULL,
    [PatientIsActive] BIT NULL,
    [PatientUpdatedDateTime] DATETIME NULL,
    [PatientRace] NVARCHAR(100) NULL,
    [PatientMedicareNumber] VARCHAR(150) NULL,
    CONSTRAINT [PK_Patients] PRIMARY KEY ([PatientID])
);
GO
