CREATE TABLE [dim].[Schedules] (
    [ScheduleID] INT IDENTITY(1,1) NOT NULL,
    [ScheduleDataSourceID] INT NULL,
    [ScheduleRoomID] VARCHAR(100) NULL,
    [ScheduleRoomSourceID] VARCHAR(100) NULL,
    [ScheduleRoomName] VARCHAR(100) NULL,
    [ScheduleLocationID] VARCHAR(100) NULL,
    [ScheduleLocationName] VARCHAR(100) NULL,
    [ScheduleDate] DATETIME NULL,
    [ScheduleDOWInMonth] INT NULL,
    [ScheduleWeekDayName] VARCHAR(100) NULL,
    [ScheduleWeekDayOrder] INT NULL,
    [ScheduleTimeSlotName] VARCHAR(100) NULL,
    [ScheduleTimeSlotStartDatetime] DATETIME NULL,
    [ScheduleTimeSlotEndDatetime] DATETIME NULL,
    [ScheduleTimeSlotMinutes] INT NULL,
    [ScheduleSlotAvailabilityType] VARCHAR(100) NULL,
    [ScheduleRoomStartTime] DATETIME NULL,
    [ScheduleRoomEndTime] DATETIME NULL,
    [ScheduleRoomProviderID] VARCHAR(100) NULL,
    [ScheduleOriginalBlockName] VARCHAR(100) NULL,
    [ScheduleCurrentBlockName] VARCHAR(100) NULL,
    [ScheduleBlockKey] VARCHAR(100) NULL,
    [ScheduleRoomComments] VARCHAR(100) NULL,
    [ScheduleBlockModifiedReason] VARCHAR(100) NULL,
    [ScheduleBlockDaysSinceRelease] INT NULL,
    [ScheduleBlockReleasedTimely] INT NULL,
    [ScheduleTimeSlotAMPMFlag] VARCHAR(10) NULL,
    [ScheduleTimeSlotUpdateDatetime] DATETIME NULL,
    CONSTRAINT [PK__Schedule__9C8A5B69833566AB] PRIMARY KEY ([ScheduleID])
);
GO
