CREATE TABLE [dim].[SQLObjects] (
    [SQLID] VARCHAR(300) NOT NULL,
    [SQLObjectName] NVARCHAR(400) NULL,
    [SQLObjectType] VARCHAR(20) NULL,
    [LoadDatetime] DATETIME2 NULL,
    CONSTRAINT [PK__SQLObjec__AB1631B9898F9794] PRIMARY KEY ([SQLID])
);
GO
