CREATE TABLE [fact].[Blocks] (
    [BlockID] VARCHAR(100) NOT NULL,
    [BlockDatasourceID] INT NULL,
    [BlockRoomID] VARCHAR(100) NULL,
    [BlockRoomSourceID] VARCHAR(100) NULL,
    [BlcokRoomName] VARCHAR(100) NULL,
    [BlockScheduleDate] DATETIME NULL,
    [BlockScheduleStartTime] DATETIME NULL,
    [BlockScheduleEndTime] DATETIME NULL,
    [BlockStartTime] DATETIME NULL,
    [BlockEndTime] DATETIME NULL,
    [BlockUpdatedStartTime] DATETIME NULL,
    [BlockUpdatedEndTime] DATETIME NULL,
    [BlockModifiedDate] DATETIME NULL,
    [BlockScheduleSlotType] VARCHAR(100) NULL,
    [BlockScheduleProviderID] VARCHAR(100) NULL,
    [BlockScheduleBlockKey] VARCHAR(100) NULL,
    [BlockOriginalName] VARCHAR(100) NULL,
    [BlockCurrentName] VARCHAR(100) NULL,
    [BlockReleaseReason] VARCHAR(100) NULL,
    [BlockModifiedReason] VARCHAR(100) NULL,
    [BlockScheduleComments] VARCHAR(100) NULL,
    [BlockDaysSinceRelease] INT NULL,
    [BlockReleasedTimely] BIT NULL,
    [BlockIsActive] BIT NULL,
    [BlockUpdatedDatetime] DATETIME NULL,
    CONSTRAINT [PK__Blocks__144215112B5445EE] PRIMARY KEY ([BlockID])
);
GO
