CREATE TABLE [fact].[VisitCaseTimes] (
    [VisitCaseTimesCaseID] VARCHAR(100) NOT NULL,
    [VisitCaseTimesDataSourceID] INT NULL,
    [VisitCaseTimesSourceID] NCHAR(50) NULL,
    [VisitCaseTimeType] VARCHAR(50) NULL,
    [VCTPreSetupStartTime] DATETIME NULL,
    [VCTPreSetupEndTime] DATETIME NULL,
    [VCTPreSetupOverbookStartTime] DATETIME NULL,
    [VCTPreSetupOverbookEndTime] DATETIME NULL,
    [VCTPreSetupInBlockStartTime] DATETIME NULL,
    [VCTPreSetupInBlockEndTime] DATETIME NULL,
    [VCTProcedureOverbookPreInBlockStartTime] DATETIME NULL,
    [VCTProcedureOverbookPreInBlockEndTime] DATETIME NULL,
    [VCTProcedureOutOfBlockPreInBlockStartTime] DATETIME NULL,
    [VCTProcedureOutOfBlockPreInBlockEndTime] DATETIME NULL,
    [VCTProcedureInBlockStartTime] DATETIME NULL,
    [VCTProcedureInBlockEndTime] DATETIME NULL,
    [VCTProcedureOverbookPostInBlockStartTime] DATETIME NULL,
    [VCTProcedureOverbookPostInBlockEndTime] DATETIME NULL,
    [VCTProcedureOutOfBlockPostInBlockStartTime] DATETIME NULL,
    [VCTProcedureOutOfBlockPostInBlockEndTime] DATETIME NULL,
    [VCTPostCleanupInBlockStartTime] DATETIME NULL,
    [VCTPostCleanupInBlockEndTime] DATETIME NULL,
    [VCTPostCleanupOverbookStartTime] DATETIME NULL,
    [VCTPostCleanupOverbookEndTime] DATETIME NULL,
    [VCTScheduleSetupStartTime] DATETIME NULL,
    [VCTScheduleSetupEndTime] DATETIME NULL,
    [VCTScheduleOverbookPreInBlockStartTime] DATETIME NULL,
    [VCTScheduleOverbookPreInBlockEndTime] DATETIME NULL,
    [VCTScheduleInBlockStartTime] DATETIME NULL,
    [VCTScheduleInBlockEndTime] DATETIME NULL,
    [VCTScheduleOutOfBlockStartTime] DATETIME NULL,
    [VCTScheduleIOutOfBlockEndTime] DATETIME NULL,
    [VCTScheduleOverbookPostInBlockStartTime] DATETIME NULL,
    [VCTScheduleOverbookPostInBlockEndTime] DATETIME NULL,
    [VCTScheduleCleanupStartTime] DATETIME NULL,
    [VCTScheculeCleanupEndTime] DATETIME NULL,
    CONSTRAINT [PK__ORCaseTimes__4D3AA1BE992C7FF3] PRIMARY KEY ([VisitCaseTimesCaseID])
);
GO
