CREATE TABLE [fact].[DenialsHB] (
    [DenialID] VARCHAR(50) NOT NULL,
    [DenialSourceID] VARCHAR(20) NULL,
    [DenialDataSourceID] INT NULL,
    [DenialTransactionID] VARCHAR(20) NULL,
    [DenialType] VARCHAR(50) NULL,
    [DenialRemitID] VARCHAR(50) NULL,
    [DenialRemitDescription] VARCHAR(MAX) NULL,
    [DenialExternalRemitCode] VARCHAR(10) NULL,
    [DenialRemarkStatus] VARCHAR(100) NULL,
    [DenialCodeGroup] VARCHAR(100) NULL,
    [DenailCodeCategory] VARCHAR(100) NULL,
    [DenialResolution] VARCHAR(100) NULL,
    [DenialSource] VARCHAR(100) NULL,
    [DenialRootCause] VARCHAR(100) NULL,
    [DenialCliniclCause] VARCHAR(100) NULL,
    [DenialPreventable] VARCHAR(50) NULL,
    [DenialDateRecieved] DATETIME NULL,
    [DenialDateCreated] DATETIME NULL,
    [DenialDaysOpen] NCHAR(10) NULL,
    [DenialDateResolved] DATETIME NULL,
    [DenialDateReopened] DATETIME NULL,
    [DenialPayerCategoryID] VARCHAR(50) NULL,
    [DenialPayerID] VARCHAR(50) NULL,
    [DenialStatus] VARCHAR(50) NULL,
    [DenialBalance] MONEY NULL,
    [DenialBucketStatus] VARCHAR(50) NULL,
    [DenialBucketFinancialClass] VARCHAR(50) NULL,
    [DenialBilledAmount] MONEY NULL,
    [DenialAllowedAmount] MONEY NULL,
    [DenialPaidAmount] MONEY NULL,
    [DenialDeniedAmount] MONEY NULL,
    [DenialAccountID] VARCHAR(50) NULL,
    [DenialPatientName] VARCHAR(100) NULL,
    [DenialBillingProviderID] VARCHAR(50) NULL,
    [DenialAccountStatus] VARCHAR(50) NULL,
    [DenialAccountBalance] MONEY NULL,
    [DenialVisitClass] VARCHAR(50) NULL,
    [DenialVisitType] VARCHAR(50) NULL,
    [DeniallocationID] VARCHAR(50) NULL,
    [DenialDepartmentID] VARCHAR(50) NULL,
    [DenialDateOfAdmission] DATETIME NULL,
    [DenialDateOfDischarge] DATETIME NULL,
    [DenialEndOfDayBucketBalance] MONEY NULL,
    [DenialRepoenDays] NCHAR(10) NULL,
    [DenialClass] VARCHAR(50) NULL,
    [DenialServiceLine] VARCHAR(100) NULL,
    [DenialWriteOffAmount] MONEY NULL,
    [DenialRecoveryAmount] MONEY NULL,
    [DenialPaymentTotal] MONEY NULL,
    [DenialUpdateDate] DATETIME NULL,
    CONSTRAINT [PK__DenialsHB__4D3AA1BE992C7FF3] PRIMARY KEY ([DenialID])
);
GO
