CREATE TABLE [fact].[VisitStatsPB] (
    [VisitStatsID] VARCHAR(100) NOT NULL,
    [VisitStatsDataSourceID] INT NULL,
    [VisitStatsProviderID] VARCHAR(50) NULL,
    [VisitStatsDepartmentID] VARCHAR(50) NULL,
    [VisitStatsDate] DATETIME NULL,
    [VisitStatsAvailableHours] DECIMAL(10,2) NULL,
    [VisitStatsBookedHours] DECIMAL(10,2) NULL,
    [VisitStatsAvailableOpeningsOnDay] INT NULL,
    [VisitStatsRegularOpeningsOnDay] INT NULL,
    [VisitStatsSameDayRegularBooked] INT NULL,
    [VisitStatsRegularBooked] INT NULL,
    [VisitStatsOverbookOpenings] INT NULL,
    [VisitStatsSameDayOverbooked] INT NULL,
    [VisitStatsOverbooked] INT NULL,
    [VisitStatsArrivedCount] INT NULL,
    [VisitStatsNoShowCount] INT NULL,
    [VisitStatsLeftWithoutBeingSeenCount] INT NULL,
    [VisitStatsCompletedCount] INT NULL,
    [VisitStatsScheduledCount] INT NULL,
    [VisitStatsCanceledCount] INT NULL,
    [VisitStatsPatientCanceledCount] INT NULL,
    [VisitStatsSameDayCanceledCount] INT NULL,
    [VisitStatsLateCanceledCount] INT NULL,
    [VisitStatsLateProviderCanceledCount] INT NULL,
    [VisitStatsRescheduledCount] INT NULL,
    [VisitStatsSameDayBooked] INT NULL,
    [VisitStatsForTodayLeadDays] INT NULL,
    [VisitStatsForTodayCount] INT NULL,
    [VisitStatsMadeTodayLeadDays] INT NULL,
    [VisitStatsMadeTodayCount] INT NULL,
    [VisitStatsRegularAvailableHours] DECIMAL(10,2) NULL,
    [VisitStatsOverbookAvailableHours] DECIMAL(10,2) NULL,
    [VisitStatsUnavailableOpeningsUsed] INT NULL,
    [VisitStatsHeldOpeningsUsed] INT NULL,
    [VisitStatsUpdateDate] DATETIME NULL,
    CONSTRAINT [PK__VisitStatsPB__4D3AA1BE992C7FF3] PRIMARY KEY ([VisitStatsID])
);
GO
