CREATE TABLE [fact].[Transactions] (
    [TransactionID] BIGINT IDENTITY(1,1) NOT NULL,
    [TransactionDatasourceID] INT NULL,
    [TransactionSourceID] VARCHAR(100) NULL,
    [TransactionParentSourceID] VARCHAR(100) NULL,
    [TransactionVisitID] VARCHAR(100) NULL,
    [TransactionEncounterID] VARCHAR(100) NULL,
    [TransactionDepartmentID] VARCHAR(100) NULL,
    [TransactionPayerID] VARCHAR(100) NULL,
    [TransactionBillingProviderID] VARCHAR(100) NULL,
    [TransactionBillingType] VARCHAR(100) NULL,
    [TransactionType] VARCHAR(100) NULL,
    [TransactionSubType] VARCHAR(100) NULL,
    [TransactionRevenueCode] VARCHAR(100) NULL,
    [TransactionRevenueCodeDescription] VARCHAR(1000) NULL,
    [TransactionCode] VARCHAR(100) NULL,
    [TransactionDescription] VARCHAR(1000) NULL,
    [TransactionCPTCode] VARCHAR(100) NULL,
    [TransactionModifier1] VARCHAR(50) NULL,
    [TransactionModifier2] VARCHAR(50) NULL,
    [TransactionModifier3] VARCHAR(50) NULL,
    [TransactionModifier4] VARCHAR(50) NULL,
    [TransactionUnits] DECIMAL(10,2) NULL,
    [TransactionAmount] MONEY NULL,
    [TransactionRVU] DECIMAL(18,2) NULL,
    [TransactionDateOfService] DATETIME NULL,
    [TransactionDateOfPosting] DATETIME NULL,
    [TransactionDateOfBilling] DATETIME NULL,
    [TransactionReportingPeriodID] VARCHAR(100) NULL,
    [TransactionStatus] VARCHAR(100) NULL,
    [TransactionIsActive] BIT NULL,
    [TransactionUpdatedDateTime] DATE NULL,
    CONSTRAINT [PK__Transact__55433A4BDAEF0418] PRIMARY KEY ([TransactionID])
);
GO
