CREATE TABLE [fact].[zzDEPRECATED_Visits] (
    [VisitID] VARCHAR(50) NOT NULL,
    [DataSourceID] INT NOT NULL,
    [VisitSourceID] VARCHAR(50) NOT NULL,
    [VisitLocationID] VARCHAR(50) NULL,
    [VisitDepartmentID] VARCHAR(50) NULL,
    [VisitBillingProviderID] VARCHAR(50) NULL,
    [VisitActualProviderID] VARCHAR(50) NULL,
    [VisitReportProviderID] VARCHAR(50) NULL,
    [VisitPracticeProviderID] VARCHAR(50) NULL,
    [VisitReferringProviderID] VARCHAR(50) NULL,
    [VisitNumber] VARCHAR(50) NOT NULL,
    [VisitDateOfService] DATE NOT NULL,
    [VisitDateOfPosting] DATE NULL,
    [VisitDateOfServiceAge] VARCHAR(50) NULL,
    [VisitDateOfServiceAgeGroup] VARCHAR(50) NULL,
    [VisitDateOfServiceAgeGroupGraph] VARCHAR(50) NULL,
    [VisitReportingPeriod] VARCHAR(50) NULL,
    [VisitReportPeriodMonth] VARCHAR(50) NULL,
    [VisitReportPeriodYear] VARCHAR(50) NULL,
    [VisitRolling13Month] VARCHAR(50) NULL,
    [VisitOrginalPayerID] VARCHAR(50) NOT NULL,
    [VisitBillingPayerID] VARCHAR(50) NULL,
    [VisitPayerCategoryOriginal] VARCHAR(50) NULL,
    [VisitPayerSubCategoryOriginal] VARCHAR(50) NULL,
    [VisitPayerCategoryCurrent] VARCHAR(50) NULL,
    [VisitPayerSubCategoryCurrent] VARCHAR(50) NULL,
    [VisitBalance] DECIMAL(18,2) NULL,
    [VisitFees] DECIMAL(18,2) NULL,
    [VisitPostedPaymenets] DECIMAL(18,2) NULL,
    [VisitSelfPayBalance] MONEY NULL,
    [VisitBalanceType] VARCHAR(50) NULL,
    [VisitProviderReimbursementPercent] VARCHAR(50) NULL,
    [VisitInfusionFlag] VARCHAR(50) NULL,
    [VisitHospitalConsultFlag] VARCHAR(50) NOT NULL,
    [VisitBalanceOverFiveFlag] VARCHAR(50) NULL,
    [VisitRadTCChargeFlag] VARCHAR(50) NULL,
    [VisitInfusionQualifierFlag] VARCHAR(50) NULL,
    [VisitPatientID] VARCHAR(50) NULL,
    [VisitCategory] VARCHAR(50) NULL,
    [VisitProviderKey] VARCHAR(200) NULL,
    [VisitProviderTransition] VARCHAR(50) NULL,
    [VisitUpdateStatus] VARCHAR(50) NULL,
    [VisitUpdateStatusValue] VARCHAR(50) NULL
);
GO
