CREATE TABLE [fact].[Accounts] (
    [AccountID] VARCHAR(100) NOT NULL,
    [AccountDataSourceID] INT NULL,
    [AccountSourceID] VARCHAR(100) NULL,
    [AccountReferenceNumber] VARCHAR(100) NULL,
    [AccountPatientID] VARCHAR(100) NULL,
    [AccountLocationID] VARCHAR(100) NULL,
    [AccountDepartmentID] VARCHAR(100) NULL,
    [AccountFinancialClassID] VARCHAR(100) NULL,
    [AccountPrimaryPayerID] VARCHAR(100) NULL,
    [AccountPrimaryPayerPlanID] VARCHAR(100) NULL,
    [AccountPrimaryProviderID] VARCHAR(100) NULL,
    [AccountAdmittingProviderID] VARCHAR(100) NULL,
    [AccountAttendingProviderID] VARCHAR(100) NULL,
    [AccountReferringProviderID] VARCHAR(100) NULL,
    [AccountDateOfService] DATE NULL,
    [AccountDateOfAdmission] DATETIME NULL,
    [AccountDateOfDischarge] DATETIME NULL,
    [AccountDateOfBilling] DATETIME NULL,
    [AccountDateOfClosing] DATETIME NULL,
    [AccountDateOfZeroBalance] DATETIME NULL,
    [AccountDateOfBadDebtWriteOff] DATETIME NULL,
    [AccountTotalCharges] MONEY NULL,
    [AccountTotalAdjustments] MONEY NULL,
    [AccountTotalPayments] MONEY NULL,
    [AccountTotalRefunds] MONEY NULL,
    [AccountTotalBalance] MONEY NULL,
    [AccountStatus] VARCHAR(100) NULL,
    [AccountClass] VARCHAR(100) NULL,
    [AccountType] VARCHAR(100) NULL,
    [AccountService] VARCHAR(100) NULL,
    [AccountBillingStatus] VARCHAR(100) NULL,
    [AccountCodingStatus] VARCHAR(100) NULL,
    [AccountCodingStatusDatetime] DATETIME NULL,
    [AccountDRG] VARCHAR(100) NULL,
    [AccountDRGDescription] VARCHAR(1000) NULL,
    [AccountDRGType] VARCHAR(100) NULL,
    [AccountDRGMDC] VARCHAR(100) NULL,
    [AccountDRGCMI] DECIMAL(18,4) NULL,
    [AccountDRGGMLOS] DECIMAL(18,2) NULL,
    [AccountIsRecurring] BIT NULL,
    [AccountIsActive] BIT NULL,
    [AccountUpdatedDatetime] DATETIME NULL,
    [AccountEmployerName] VARCHAR(100) NULL,
    [AccountBeneficiaryNumber] VARCHAR(100) NULL,
    [AccountGuarantorName] NVARCHAR(155) NULL,
    [AccountGuarantorID] VARCHAR(155) NULL,
    CONSTRAINT [PK__Accounts__4D3AA1BE992C7FF3] PRIMARY KEY ([AccountID])
);
GO
