CREATE TABLE [fact].[Claims] (
    [ClaimID] VARCHAR(50) NOT NULL,
    [ClaimDataSourceID] INT NULL,
    [ClaimSourceID] VARCHAR(50) NULL,
    [ClaimAcceptanceDate] DATETIME NULL,
    [ClaimDateOfService] DATETIME NULL,
    [ClaimFromDate] DATETIME NULL,
    [ClaimThroughDate] DATETIME NULL,
    [ClaimPayorID] VARCHAR(50) NULL,
    [ClaimPlanID] VARCHAR(50) NULL,
    [ClaimCoverageID] VARCHAR(50) NULL,
    [ClaimDefinitionID] VARCHAR(50) NULL,
    [ClaimInvoiceNumber] VARCHAR(50) NULL,
    [ClaimPatientID] VARCHAR(50) NULL,
    [ClaimProviderID] VARCHAR(50) NULL,
    [ClaimAccountID] VARCHAR(50) NULL,
    [ClaimLiabilityBucketID] VARCHAR(50) NULL,
    [ClaimLocationID] VARCHAR(50) NULL,
    [ClaimDepartmentID] VARCHAR(50) NULL,
    [ClaimConditionCode] VARCHAR(10) NULL,
    [ClaimConditionCodeDescription] VARCHAR(100) NULL,
    [ClaimFormType] VARCHAR(50) NULL,
    [ClaimType] VARCHAR(50) NULL,
    [ClaimAccountType] VARCHAR(50) NULL,
    [ClaimClassType] VARCHAR(50) NULL,
    [ClaimTotalCharges] MONEY NULL,
    [ClaimTotalDue] MONEY NULL,
    [ClaimNonCoveredAmount] MONEY NULL,
    [ClaimTotalPayments] MONEY NULL,
    [ClaimTotalAdjustments] MONEY NULL,
    [ClaimBillType] VARCHAR(50) NULL,
    [ClaimUpdateDateTime] DATETIME NULL,
    CONSTRAINT [PK__Claims__EF2E13BBBA532C1E] PRIMARY KEY ([ClaimID])
);
GO
