CREATE TABLE [fact].[Visits2] (
    [VisitID] VARCHAR(100) NOT NULL,
    [VisitDatasourceID] INT NULL,
    [VisitSourceID] VARCHAR(100) NULL,
    [VisitPatientID] VARCHAR(100) NULL,
    [VisitAccountID] VARCHAR(100) NULL,
    [VisitLocationID] VARCHAR(100) NULL,
    [VisitDepartmentID] VARCHAR(100) NULL,
    [VisitRoomID] VARCHAR(100) NULL,
    [VisitPrimaryProviderID] VARCHAR(100) NULL,
    [VisitAppointmentProviderID] VARCHAR(100) NULL,
    [VisitAdmittingProviderID] VARCHAR(100) NULL,
    [VisitAttendingProviderID] VARCHAR(100) NULL,
    [VisitDischargeProviderID] VARCHAR(100) NULL,
    [VisitType] VARCHAR(100) NULL,
    [VisitService] VARCHAR(100) NULL,
    [VisitStatus] VARCHAR(100) NULL,
    [VisitDateOfService] DATE NULL,
    [VisitDatetimeOfService] DATETIME NULL,
    [VisitDateOfScheduling] DATETIME NULL,
    [VisitDateOfAppointment] DATETIME NULL,
    [VisitDateOfAdmission] DATETIME NULL,
    [VisitDateOfDischarge] DATETIME NULL,
    [VisitDateofClosing] DATETIME NULL,
    [VisitDateOfCancellation] DATETIME NULL,
    [VisitCancellationReason] VARCHAR(100) NULL,
    [VisitIsPrimary] BIT NULL,
    [VisitIsActive] BIT NULL,
    [VisitUpdatedDatetime] DATETIME NULL,
    CONSTRAINT [PK__Visits2__4D3AA1BEE8E53509] PRIMARY KEY ([VisitID])
);
GO
