CREATE TABLE [fact].[DenialsPB] (
    [DenialID] VARCHAR(50) NOT NULL,
    [DenialDataSourceID] TINYINT NULL,
    [DenialTransactionID] VARCHAR(20) NULL,
    [DenialTransactionChargeID] VARCHAR(20) NULL,
    [ChargePostingDate] DATE NULL,
    [ChargeServiceDate] DATE NULL,
    [DenialReceiveDate] DATETIME NULL,
    [DenialProcedureID] VARCHAR(20) NULL,
    [DenialPatientID] VARCHAR(20) NULL,
    [DenialLocationID] VARCHAR(20) NULL,
    [DenialDepartmentID] VARCHAR(20) NULL,
    [DenialBillingProviderID] VARCHAR(20) NULL,
    [DenialServiceProviderID] VARCHAR(20) NULL,
    [DenialPayerID] VARCHAR(20) NULL,
    [DenialPayerPlanID] VARCHAR(20) NULL,
    [DenialProcedureCode] VARCHAR(20) NULL,
    [DenialDiagnosisID] VARCHAR(20) NULL,
    [DenialInvoiceNumber] VARCHAR(20) NULL,
    [DenialReasonCode] VARCHAR(20) NULL,
    [DenialReasonDescription] VARCHAR(200) NULL,
    [DenialCategory] VARCHAR(50) NULL,
    [DenialCause] VARCHAR(50) NULL,
    [DenialRootCause] VARCHAR(100) NULL,
    [DenialReasonGroup] VARCHAR(50) NULL,
    [DenialResolutionCategory] VARCHAR(50) NULL,
    [DenialStatus] VARCHAR(20) NULL,
    [DenialIsPrimary] VARCHAR(20) NULL,
    [DenialIsFirst] VARCHAR(20) NULL,
    [DenialPostingDate] DATE NULL,
    [DenialCompletionDate] DATE NULL,
    [DenialDaysToClose] BIGINT NULL,
    [DenialAmount] MONEY NULL,
    [DenialRecoveryAmount] MONEY NULL,
    [DenialAdjustmentAmount] MONEY NULL,
    [DenialBillingAmount] MONEY NULL,
    [DenialUpdateDate] DATETIME NULL
);
GO
