CREATE TABLE [fact].[TransactionsPB] (
    [TransactionID] VARCHAR(100) NOT NULL,
    [TransactionDatasourceID] INT NULL,
    [TransactionSourceID] VARCHAR(100) NULL,
    [TransactionParentSourceID] VARCHAR(100) NULL,
    [TransactionVisitID] VARCHAR(100) NULL,
    [TransactionAccountID] VARCHAR(100) NULL,
    [TransactionDepartmentID] VARCHAR(100) NULL,
    [TransactionPayerID] VARCHAR(100) NULL,
    [TransactionBillingProviderID] VARCHAR(100) NULL,
    [TransactionBillingType] VARCHAR(100) NULL,
    [TransactionType] VARCHAR(100) NULL,
    [TransactionSubType] VARCHAR(100) NULL,
    [TransactionRevenueCode] VARCHAR(100) NULL,
    [TransactionRevenueCodeDescription] VARCHAR(1000) NULL,
    [TransactionCode] VARCHAR(100) NULL,
    [TransactionDescription] VARCHAR(1000) NULL,
    [TransactionCPTCode] VARCHAR(100) NULL,
    [TransactionCPTDescription] VARCHAR(1000) NULL,
    [TransactionModifier1] VARCHAR(50) NULL,
    [TransactionModifier2] VARCHAR(50) NULL,
    [TransactionModifier3] VARCHAR(50) NULL,
    [TransactionModifier4] VARCHAR(50) NULL,
    [TransactionICD10Dx1] VARCHAR(50) NULL,
    [TransactionICD10Dx2] VARCHAR(50) NULL,
    [TransactionICD10Dx3] VARCHAR(50) NULL,
    [TransactionICD10Dx4] VARCHAR(50) NULL,
    [TransactionICD10Dx5] VARCHAR(50) NULL,
    [TransactionUnits] DECIMAL(10,2) NULL,
    [TransactionAmount] MONEY NULL,
    [TransactionRVU] DECIMAL(18,2) NULL,
    [TransactionDateOfService] DATETIME NULL,
    [TransactionDateOfPosting] DATETIME NULL,
    [TransactionDateOfBilling] DATETIME NULL,
    [TransactionDateOfVoid] DATETIME NULL,
    [TransactionReportingPeriodID] VARCHAR(100) NULL,
    [TransactionPlaceOfServiceCode] VARCHAR(50) NULL,
    [TransactionPlaceOfServiceType] VARCHAR(100) NULL,
    [TransactionPatientID] VARCHAR(50) NULL,
    [TransactionGLType] VARCHAR(10) NULL,
    [TransactionStatus] VARCHAR(100) NULL,
    [TransactionIsActive] BIT NULL,
    [TransactionUpdatedDateTime] DATE NULL,
    [TransactionPayerPlanID] VARCHAR(50) NULL,
    [TransactionPlaceOfService] VARCHAR(100) NULL,
    [TransactionActiveARAmount] MONEY NULL,
    CONSTRAINT [PK__Transact__55433A4B1E5888A4] PRIMARY KEY ([TransactionID])
);
GO
