CREATE TABLE [fact].[zzzDEPRECATED_Visits] (
    [VisitID] VARCHAR(100) NOT NULL,
    [VisitDataSourceID] INT NULL,
    [VisitSourceID] VARCHAR(100) NULL,
    [VisitReferenceNumber] VARCHAR(100) NULL,
    [VisitPatientID] VARCHAR(100) NULL,
    [VisitLocationID] VARCHAR(100) NULL,
    [VisitDepartmentID] VARCHAR(100) NULL,
    [VisitRoom] VARCHAR(100) NULL,
    [VisitPrimaryDiagnosis] VARCHAR(300) NULL,
    [VisitPrimaryProcedureCode] VARCHAR(300) NULL,
    [VisitPrimaryPayerID] VARCHAR(100) NULL,
    [VisitPrimaryPayerPlanID] VARCHAR(100) NULL,
    [VisitPrimaryProviderID] VARCHAR(100) NULL,
    [VisitAdmittingProviderID] VARCHAR(100) NULL,
    [VisitAttendingProviderID] VARCHAR(100) NULL,
    [VisitReferringProviderID] VARCHAR(100) NULL,
    [VisitDateOfService] DATE NULL,
    [VisitDateOfScheduling] DATETIME NULL,
    [VisitDateOfRegistration] DATETIME NULL,
    [VisitDateOfAdmission] DATETIME NULL,
    [VisitDateOfDischarge] DATETIME NULL,
    [VisitDateOfBilling] DATETIME NULL,
    [VisitDateOfClosing] DATETIME NULL,
    [VisitDateOfCancellation] DATETIME NULL,
    [VisitDateOfZeroBalance] DATETIME NULL,
    [VisitDateOfBadDebtWriteOff] DATETIME NULL,
    [VisitCancelledReason] VARCHAR(100) NULL,
    [VisitStatus] VARCHAR(100) NULL,
    [VisitClass] VARCHAR(100) NULL,
    [VisitType] VARCHAR(100) NULL,
    [VisitReason] VARCHAR(100) NULL,
    [VisitBillingStatus] VARCHAR(100) NULL,
    [VisitBillingFlag] VARCHAR(50) NULL,
    [VisitTotalCharges] MONEY NULL,
    [VisitTotalAdjustments] MONEY NULL,
    [VisitTotalPayments] MONEY NULL,
    [VisitTotalRefunds] MONEY NULL,
    [VisitTotalBalance] MONEY NULL,
    [VisitAdmittedFrom] VARCHAR(100) NULL,
    [VisitDischargedTo] VARCHAR(100) NULL,
    [VisitDRG] VARCHAR(100) NULL,
    [VisitDRGDescription] VARCHAR(300) NULL,
    [VisitDRGType] VARCHAR(100) NULL,
    [VisitDRGMDC] VARCHAR(50) NULL,
    [VisitIsSurgical] BIT NULL,
    [VisitIsActive] BIT NULL,
    [VisitUpdatedDatetime] DATETIME NULL,
    CONSTRAINT [PK__Visits__4D3AA1BE992C7FF3] PRIMARY KEY ([VisitID])
);
GO
