CREATE TABLE [fact].[VisitSchedulePB] (
    [VisitScheduleVisitID] VARCHAR(50) NOT NULL,
    [VisitScheduleDataSourceID] INT NULL,
    [VisitScheduleSourceID] VARCHAR(50) NULL,
    [VisitScheduleAccountID] VARCHAR(50) NULL,
    [VisitScheduleDate] DATETIME NULL,
    [VisitSchedulePatientID] VARCHAR(50) NULL,
    [VisitScheduleStatus] VARCHAR(50) NULL,
    [VisitScheduleDepartmentID] VARCHAR(50) NULL,
    [VisitScheduleSpecialty] VARCHAR(50) NULL,
    [VisitScheduleLocationID] VARCHAR(50) NULL,
    [VisitScheduleProviderID] VARCHAR(50) NULL,
    [VisitSchedulePayerID] VARCHAR(50) NULL,
    [VisitScheduleType] VARCHAR(50) NULL,
    [VisitScheduleScheduleDate] DATETIME NULL,
    [VisitScheduleAppointmentDate] DATETIME NULL,
    [VisitScheduleCheckinTime] DATETIME NULL,
    [VisitScheduleInRoomTime] DATETIME NULL,
    [VisitScheduleProviderInTime] DATETIME NULL,
    [VisitScheduleEndTime] DATETIME NULL,
    [VisitScheduleCheckoutTime] DATETIME NULL,
    [VisitScheduleTimeToRoom] INT NULL,
    [VisitScheduleTimeInRoom] INT NULL,
    [VisitScheduleVisitDuration] INT NULL,
    [VisitScheduleSameDayCancellation] VARCHAR(10) NULL,
    [VisitScheduleConfirmationStatus] VARCHAR(50) NULL,
    [VisitScheduleConfirmationDate] DATETIME NULL,
    [VisitScheduleOverbook] VARCHAR(10) NULL,
    [VisitScheduleCancellationDate] DATETIME NULL,
    [VisitScheduleLateCancellation] VARCHAR(10) NULL,
    [VisitScheduleCopayDue] MONEY NULL,
    [VisitScheduleCopayCollected] MONEY NULL,
    [VisitScheduleUpdateDate] DATETIME NULL,
    CONSTRAINT [PK__VisitSchedulePB__4D3AA1BE992C7FF3] PRIMARY KEY ([VisitScheduleVisitID])
);
GO
