CREATE TABLE [fact].[CaseSchedule] (
    [CaseScheduleID] VARCHAR(100) NOT NULL,
    [CaseScheduleDataSourceID] INT NULL,
    [CaseScheduleAction] VARCHAR(50) NULL,
    [CaseScheduleStatus] VARCHAR(50) NULL,
    [CaseScheduleVisitVolume] INT NULL,
    [CaseScheduleCancellationAgeCategory] VARCHAR(100) NULL,
    [CaseScheduleDaysFromCancellation] INT NULL,
    [CaseScheduleDateOfAction] DATETIME NULL,
    [CaseScheduleDateOfReschedule] DATETIME NULL,
    [CaseScheduleDateOfCase] DATETIME NULL,
    [CaseScheduleCancellationReason] VARCHAR(100) NULL,
    [CaseScheduleDateOfCancellation] DATETIME NULL,
    [CaseScheduleCencellationComments] VARCHAR(MAX) NULL,
    [CaseScheduleRescheduleComments] VARCHAR(MAX) NULL,
    [CaseScheduleNotPerformedReason] VARCHAR(100) NULL,
    [CaseScheduleNotPerformedComments] VARCHAR(MAX) NULL,
    [CaseScheduleProviderID] VARCHAR(50) NULL,
    [CaseScheduleParentProviderID] VARCHAR(50) NULL,
    [CaseScheduleProviderName] VARCHAR(100) NULL,
    [CaseScheduleAnesthesiaProviderID] VARCHAR(50) NULL,
    [CaseScheduleAnesthesiaProviderName] VARCHAR(100) NULL,
    [CaseScheduleServiceLine] VARCHAR(100) NULL,
    [CaseSchedueVisitType] VARCHAR(50) NULL,
    [CaseScheduleVisitClass] VARCHAR(50) NULL,
    [CaseSchedulePrimaryProcedure] VARCHAR(MAX) NULL,
    [CaseScheduleLocationID] VARCHAR(50) NULL
);
GO
