CREATE TABLE [fact].[Encounters] (
    [EncounterID] VARCHAR(100) NOT NULL,
    [EncounterDataSourceID] INT NULL,
    [EncounterSourceID] VARCHAR(100) NULL,
    [ParentEncounterID] VARCHAR(100) NULL,
    [EncounterVisitID] VARCHAR(100) NULL,
    [EncounterPatientID] VARCHAR(100) NULL,
    [EncounterLocationID] VARCHAR(100) NULL,
    [EncounterDepartmentID] VARCHAR(100) NULL,
    [EncounterRoom] VARCHAR(100) NULL,
    [EncounterPrimaryProviderID] VARCHAR(100) NULL,
    [EncounterAdmittingProviderID] VARCHAR(100) NULL,
    [EncounterAttendingProviderID] VARCHAR(100) NULL,
    [EncounterReferringProviderID] VARCHAR(100) NULL,
    [EncounterDateOfService] DATE NULL,
    [EncounterDateOfScheduling] DATETIME NULL,
    [EncounterDateOfRegistration] DATETIME NULL,
    [EncounterBeginDatetime] DATETIME NULL,
    [EncounterEndDatetime] DATETIME NULL,
    [EncounterDateOfCancellation] DATETIME NULL,
    [EncounterCancelledReason] VARCHAR(100) NULL,
    [EncounterStatus] VARCHAR(100) NULL,
    [EncounterClass] VARCHAR(100) NULL,
    [EncounterType] VARCHAR(100) NULL,
    [EncounterReason] VARCHAR(1000) NULL,
    [EncounterIsSurgical] BIT NULL,
    [EncounterIsActive] BIT NULL,
    [EncounterUpdatedDatetime] DATETIME NULL,
    CONSTRAINT [PK__Encounters__4D3AA1BE992C7FF3] PRIMARY KEY ([EncounterID])
);
GO
