CREATE TABLE [hero].[PracticeProviderss] (
    [Id] INT NOT NULL,
    [PracticeID] INT NOT NULL,
    [ProviderID] INT NOT NULL,
    [PracticeProviderIsDefaultPractice] BIT NOT NULL,
    [PracticeProviderIsDefaultReferralPractice] BIT NOT NULL,
    [PracticeProviderIsPrimary] BIT NOT NULL,
    [PracticeProviderIsSpecialist] BIT NOT NULL,
    [PracticeProviderIsMidLevel] BIT NOT NULL,
    [PracticeProviderIsReferralTarget] BIT NOT NULL,
    [PracticeProviderIsAffiliate] BIT NOT NULL,
    [PracticeProviderEffectiveDate] DATETIME2 NOT NULL,
    [PracticeProviderEndDate] DATETIME2 NOT NULL,
    [PracticeProviderFTE] FLOAT NOT NULL,
    [PracticeProviderAllocationPercent] FLOAT NOT NULL,
    [PracticeProviderLocation] INT NOT NULL,
    [PracticeProviderGLType] NVARCHAR(MAX) NOT NULL,
    [PracticeProviderGLTypeID] INT NOT NULL,
    [PracticeProviderGLProviderID] NVARCHAR(MAX) NOT NULL,
    [PracticeProviderDHSType] INT NOT NULL,
    [PracticeProviderID] FLOAT NOT NULL,
    [EpicPracticeProviderID] FLOAT NOT NULL,
    [PracticeProviderIsActive] BIT NOT NULL,
    [PracticeProviderUpdatedDatetime] DATETIME2 NOT NULL,
    [CreatedDate] DATETIME2 NULL,
    [ModifiedDate] DATETIME2 NULL,
    [ModifiedBy] NVARCHAR(MAX) NULL,
    [DeletedDate] DATETIME2 NULL,
    [DeletedBy] NVARCHAR(MAX) NULL,
    [IsDeleted] BIT NOT NULL,
    [IsActive] BIT NOT NULL
);
GO
