CREATE TABLE [hero].[Providerss] (
    [ProviderID] INT NOT NULL,
    [ProviderProviderID] NVARCHAR(MAX) NOT NULL,
    [ProviderDataSourceID] FLOAT NOT NULL,
    [ProviderSourceID] NVARCHAR(MAX) NOT NULL,
    [ProviderAbbreviation] NVARCHAR(MAX) NOT NULL,
    [ProviderFirstName] NVARCHAR(MAX) NOT NULL,
    [ProviderMiddleInitial] NVARCHAR(MAX) NOT NULL,
    [ProviderLastName] NVARCHAR(MAX) NOT NULL,
    [ProviderGender] NVARCHAR(MAX) NOT NULL,
    [ProviderSuffix] NVARCHAR(MAX) NOT NULL,
    [ProviderStreetAddress1] NVARCHAR(MAX) NOT NULL,
    [ProviderStreetAddress2] NVARCHAR(MAX) NOT NULL,
    [ProviderCity] NVARCHAR(MAX) NOT NULL,
    [ProviderState] NVARCHAR(MAX) NOT NULL,
    [ProviderZipCode] NVARCHAR(MAX) NOT NULL,
    [ProviderPhone] NVARCHAR(MAX) NOT NULL,
    [ProviderFax] NVARCHAR(MAX) NOT NULL,
    [ProviderSpecialtyID] INT NOT NULL,
    [ProviderUPIN] NVARCHAR(MAX) NOT NULL,
    [ProviderNPI] NVARCHAR(MAX) NOT NULL,
    [ProviderIsActive] BIT NOT NULL,
    [ProviderUpdatedDateTime] DATETIME2 NOT NULL,
    [IsDeleted] BIT NOT NULL,
    [CreatedDate] DATETIME2 NULL,
    [ModifiedDate] DATETIME2 NULL,
    [ModifiedBy] NVARCHAR(MAX) NULL,
    [DeletedDate] DATETIME2 NULL,
    [DeletedBy] NVARCHAR(MAX) NULL,
    [IsActive] BIT NOT NULL
);
GO
