CREATE TABLE [hero].[Practicess] (
    [PracticeID] INT NOT NULL,
    [PracticePracticeID] NVARCHAR(MAX) NULL,
    [PracticeDataSourceID] FLOAT NULL,
    [PracticeSourceID] NVARCHAR(MAX) NULL,
    [PracticeName] NVARCHAR(MAX) NOT NULL,
    [PracticeAbbreviation] NVARCHAR(MAX) NULL,
    [PracticeDataSource] NVARCHAR(MAX) NULL,
    [PracticeIsActive] BIT NOT NULL,
    [PracticeUpdatedDatetime] DATETIME2 NULL,
    [PracticeGLLocationID] NVARCHAR(MAX) NULL,
    [PracticeGLLocation] NVARCHAR(MAX) NULL,
    [PracticeGLPracticeID] NVARCHAR(MAX) NULL,
    [PracticeSpecialtyId] INT NULL,
    [PracticeCompanyId] INT NULL,
    [SpecialtyID] INT NULL,
    [ValidFrom] DATETIME2 NULL,
    [ValidTo] DATETIME2 NULL,
    [CreatedDate] DATETIME2 NULL,
    [ModifiedDate] DATETIME2 NULL,
    [ModifiedBy] NVARCHAR(MAX) NULL,
    [DeletedDate] DATETIME2 NULL,
    [DeletedBy] NVARCHAR(MAX) NULL,
    [IsDeleted] BIT NOT NULL,
    [ApApproverUserIds] NVARCHAR(MAX) NULL,
    [ApPreparerUserIds] NVARCHAR(MAX) NULL,
    [IsActive] BIT NOT NULL,
    [CompanyID] INT NULL,
    [RequiredPermissions] NVARCHAR(MAX) NOT NULL,
    [DepartmentId] INT NULL,
    [SameStoreEndDate] DATETIME2 NULL,
    [SameStoreStartDate] DATETIME2 NULL,
    [AccountIDFromGreatPlains] INT NULL,
    [IncludeInBlueBooks] BIT NOT NULL
);
GO
