CREATE TABLE [rpt].[EKKInvoices] (
    [EKKInvoiceID] VARCHAR(100) NOT NULL,
    [EKKInvoiceDatasourceID] INT NULL,
    [EKKInvoiceSourceID] VARCHAR(100) NULL,
    [EKKInvoiceDateOfService] DATETIME NULL,
    [EKKInvoiceActualProvider] VARCHAR(100) NULL,
    [EKKInvoiceUpdateStatus] VARCHAR(100) NULL,
    [EKKInvoiceDepartment] VARCHAR(100) NULL,
    [EKKInvoiceProcedureDescription] VARCHAR(100) NULL,
    [EKKInvoiceProcedureModifier] VARCHAR(100) NULL,
    [EKKInvoiceModifier] VARCHAR(100) NULL,
    [EKKInvoiceProcedureCode] VARCHAR(100) NULL,
    [EKKInvoiceUnits] VARCHAR(100) NULL,
    [EKKInvoiceVoucherNumber] VARCHAR(100) NULL,
    [EKKInvoiceClaimNumber] VARCHAR(100) NULL,
    [EKKInvoiceServiceFee] MONEY NULL,
    [EKKInvoicePatientNumber] VARCHAR(100) NULL,
    [EKKInvoicePrimaryDiagCode] VARCHAR(100) NULL,
    [EKKInvoiceSecondDiagnosisCode] VARCHAR(100) NULL,
    [EKKInvoiceThirdDiagnosisCode] VARCHAR(100) NULL,
    [EKKInvoiceNDC] VARCHAR(100) NULL,
    [EKKInvoicePatientName] VARCHAR(100) NULL,
    [EKKInvoicePolicyNumber] VARCHAR(100) NULL,
    [EKKInvoicePolicyCertificate] VARCHAR(100) NULL,
    [EKKPayerName] VARCHAR(100) NULL,
    [EKKInvoiceAddress1] VARCHAR(100) NULL,
    [EKKInvoiceAddress2] VARCHAR(100) NULL,
    [EKKInvoiceCity] VARCHAR(100) NULL,
    [EKKInvoiceState] VARCHAR(100) NULL,
    [EKKInvoiceZip] VARCHAR(100) NULL,
    [EKKInvoiceIsActive] BIT NULL,
    [EKKInvoiceUpdateDatetime] DATETIME NULL,
    CONSTRAINT [PK__EKKInvoi__D60C9640572DD923] PRIMARY KEY ([EKKInvoiceID])
);
GO
