CREATE TABLE [rpt].[ARHistoryPB] (
    [ARHistoryID] VARCHAR(100) NOT NULL,
    [ARHistoryDate] DATE NULL,
    [TransactionDataSourceID] INT NULL,
    [TransactionSourceID] VARCHAR(50) NULL,
    [TransactionType] VARCHAR(50) NULL,
    [TransactionLocationID] VARCHAR(50) NULL,
    [TransactionDepartmentID] VARCHAR(50) NULL,
    [TransactionPlaceOfServiceID] VARCHAR(50) NULL,
    [TransactionPlaceOfServiceType] VARCHAR(50) NULL,
    [TransactionGuarantorID] VARCHAR(50) NULL,
    [TransactionGuarantorType] VARCHAR(50) NULL,
    [TransactionAccountID] VARCHAR(50) NULL,
    [TransactionAccountClass] VARCHAR(50) NULL,
    [TransactionVisitID] VARCHAR(50) NULL,
    [TransactionVisitType] VARCHAR(50) NULL,
    [CurrentFinancialClass] VARCHAR(50) NULL,
    [CurrentPayerID] VARCHAR(50) NULL,
    [CurrentPayerPlanID] VARCHAR(50) NULL,
    [OriginalFinancialClass] VARCHAR(50) NULL,
    [OriginalPayerID] VARCHAR(50) NULL,
    [OriginalPayerPlanID] VARCHAR(50) NULL,
    [TransactionServiceProviderID] VARCHAR(50) NULL,
    [TransactionBillingProviderID] VARCHAR(50) NULL,
    [TransactionCode] VARCHAR(50) NULL,
    [TransactionDescription] VARCHAR(300) NULL,
    [TransactionCPTCode] VARCHAR(30) NULL,
    [TransactionModifier1] VARCHAR(30) NULL,
    [TransactionModifier2] VARCHAR(30) NULL,
    [TransactionModifier3] VARCHAR(30) NULL,
    [TransactionModifier4] VARCHAR(30) NULL,
    [TransactionUnits] DECIMAL(18,2) NULL,
    [TransactionLedgerType] VARCHAR(30) NULL,
    [TransactionOriginalAmount] MONEY NULL,
    [TransactionARAmountAll] MONEY NULL,
    [TransactionARAmountSelfPay] MONEY NULL,
    [TransactionARAmountInsurance] MONEY NULL,
    [TransactionARAmountActive] MONEY NULL,
    [TransactionARAmountBadDebt] MONEY NULL,
    [TransactionServiceDate] DATE NULL,
    [TransactionServiceDateAge] INT NULL,
    [TransactionPostDate] DATE NULL,
    [TransactionPostDateAge] INT NULL,
    [TransactionInsuranceAgeDate] DATE NULL,
    [TransactionInsuranceAge] INT NULL,
    [TransactionFirstClaimDate] DATE NULL,
    [TransactionLastClaimDate] DATE NULL,
    [TransactionSelfPayAgeDate] DATE NULL,
    [TransactionSelfPayAge] INT NULL,
    [ARHistoryUpdatedDatetime] DATETIME NULL,
    CONSTRAINT [PK__ARHistor__133B738A1CD5F6E7] PRIMARY KEY ([ARHistoryID])
);
GO
