CREATE TABLE [stg].[ModMed_Charges] (
    [charges_id] VARCHAR(100) NULL,
    [charge_link_key] VARCHAR(100) NULL,
    [service_date_from_ld] DATETIME2 NULL,
    [post_date_ld] DATETIME2 NULL,
    [primary_provider_id] VARCHAR(100) NULL,
    [provider_level_adjustment_id] VARCHAR(100) NULL,
    [appointment_provider_id] VARCHAR(100) NULL,
    [provider_id] VARCHAR(100) NULL,
    [payer_id] VARCHAR(100) NULL,
    [insurance_policy_id] VARCHAR(100) NULL,
    [patient_id] VARCHAR(100) NULL,
    [facility_id] VARCHAR(100) NULL,
    [appointment_id] VARCHAR(100) NULL,
    [ledger_charge_amount] MONEY NULL,
    [ledger_units] DECIMAL(18,2) NULL,
    [cpt_product] VARCHAR(100) NULL,
    [cpt_product_description] VARCHAR(500) NULL,
    [code_category] VARCHAR(100) NULL,
    [service_location_pos_code] VARCHAR(50) NULL,
    [bill_id] VARCHAR(100) NULL,
    [original_bill_id] VARCHAR(100) NULL,
    [bill_item_id] VARCHAR(100) NULL,
    [bill_type] VARCHAR(100) NULL,
    [bill_status] VARCHAR(100) NULL,
    [financial_category] VARCHAR(100) NULL,
    [LoadDateTime] DATETIME2 NULL,
    [activity_type] VARCHAR(200) NULL,
    [coverage_type] NVARCHAR(300) NULL
);
GO
