CREATE TABLE [stg].[APMTransactions] (
    [TransactionID] VARCHAR(50) NOT NULL,
    [DataSourceID] INT NOT NULL,
    [SourceTransactionID] VARCHAR(50) NOT NULL,
    [TransactionPatientID] VARCHAR(50) NOT NULL,
    [TransactionVisitID] VARCHAR(50) NOT NULL,
    [TransactionType] VARCHAR(100) NULL,
    [TransactionUpdateStatus] VARCHAR(100) NULL,
    [TransactionDateOfPosting] DATE NULL,
    [TransactionDateOfService] DATE NULL,
    [TransactionReportingPeriodMonth] INT NULL,
    [TransactionReportingPeriodYear] INT NULL,
    [TransactionReferringProviderID] VARCHAR(50) NULL,
    [TransactionReportProviderID] VARCHAR(50) NULL,
    [TransactionPracticeProviderID] VARCHAR(50) NULL,
    [TransactionDepartmentID] VARCHAR(50) NULL,
    [TransactionProcedureCode] VARCHAR(50) NULL,
    [TransactionProcedureCategory] VARCHAR(50) NULL,
    [TransactionUnits] INT NULL,
    [TransactionAmount] MONEY NULL,
    [TransactionLocationID] VARCHAR(50) NULL,
    [TransactionCodeDescription] VARCHAR(50) NULL,
    [TransactionPayerSubCategory] VARCHAR(50) NULL,
    [TransactionBillingProviderType] VARCHAR(50) NULL,
    [TransactionActualProviderType] VARCHAR(50) NULL,
    [TransactionWorksForProviderID] VARCHAR(50) NULL,
    [TransactionPostingYear] INT NULL,
    [TransactionPostingMonth] INT NULL,
    [TransactionPointOfServiceType] VARCHAR(50) NULL,
    [TransactionPointOfServiceSurgical] VARCHAR(50) NULL,
    [TransactionVisitCategory] VARCHAR(50) NULL,
    [TransactionVoidKey] VARCHAR(50) NULL,
    [TransactionVoided] VARCHAR(50) NULL,
    [TransactionServicePaymentID] VARCHAR(50) NULL,
    [TransactionProcedureCategoryAbbreviation] VARCHAR(50) NULL
);
GO
