CREATE TABLE [stg].[ModMed_Payments] (
    [payments_posted_id] VARCHAR(100) NULL,
    [bill_id] VARCHAR(100) NULL,
    [bill_item_id] VARCHAR(100) NULL,
    [patient_id] VARCHAR(100) NULL,
    [payer_id] VARCHAR(100) NULL,
    [provider_id] VARCHAR(100) NULL,
    [insurance_policy_id] VARCHAR(100) NULL,
    [facility_id] VARCHAR(100) NULL,
    [primary_provider_id] VARCHAR(100) NULL,
    [ledger_payment_amount] DECIMAL(18,2) NULL,
    [payment_method] VARCHAR(100) NULL,
    [payment_source] VARCHAR(100) NULL,
    [cpt_product] VARCHAR(50) NULL,
    [cpt_product_description] VARCHAR(255) NULL,
    [payment_code] VARCHAR(50) NULL,
    [payment_code_description] VARCHAR(255) NULL,
    [code_category] VARCHAR(100) NULL,
    [service_date_from_ld] DATETIME NULL,
    [ledger_activity_date] DATETIME NULL,
    [post_date_ld] DATETIME NULL,
    [ledger_activity_date_ld] DATETIME NULL,
    [service_location_pos_code] VARCHAR(10) NULL,
    [link_state] VARCHAR(50) NULL,
    [auto_pay_bill_status] VARCHAR(50) NULL,
    [appointment_provider_id] VARCHAR(100) NULL,
    [batch_id] VARCHAR(100) NULL,
    [batch_name] VARCHAR(255) NULL,
    [LoadDateTime] DATETIME NULL DEFAULT (sysdatetime()),
    [charge_link_key] VARCHAR(100) NULL,
    [wrvu] DECIMAL(9,2) NULL,
    [practice_location_id] VARCHAR(100) NULL,
    [activity_type] VARCHAR(100) NULL,
    [check_number] VARCHAR(150) NULL,
    [deposit_date_ld] DATETIME NULL,
    [payment_link_key] VARCHAR(255) NULL
);
GO
