CREATE TABLE [stg].[ModMed_Payers] (
    [payer_id] VARCHAR(100) NULL,
    [firm_id] VARCHAR(100) NULL,
    [financial_category_id] VARCHAR(100) NULL,
    [payment_payer_id_number] VARCHAR(200) NULL,
    [payer_id_number] VARCHAR(200) NULL,
    [eligibility_payer_id_number] VARCHAR(200) NULL,
    [dme_payer_id_number] VARCHAR(200) NULL,
    [institutional_payer_id_number] VARCHAR(200) NULL,
    [other_payer_id_number] VARCHAR(200) NULL,
    [payer_name] VARCHAR(300) NULL,
    [financial_category_name] VARCHAR(300) NULL,
    [facility_submission_form] VARCHAR(200) NULL,
    [eligibility_provider_identification_strategy] VARCHAR(200) NULL,
    [claim_provider_identification_strategy] VARCHAR(200) NULL,
    [primary_default_format] VARCHAR(200) NULL,
    [primary_print_by_clearinghouse] BIT NULL,
    [sequential_default_format] VARCHAR(200) NULL,
    [sequential_print_by_clearinghouse] BIT NULL,
    [workers_comp_default_format] VARCHAR(200) NULL,
    [auto_pip_default_format] VARCHAR(200) NULL,
    [vision_default_format] VARCHAR(200) NULL,
    [contracted] BIT NULL,
    [accepts_assignment] BIT NULL,
    [is_medical] BIT NULL,
    [is_workers_comp] BIT NULL,
    [is_auto_pip] BIT NULL,
    [is_vision] BIT NULL,
    [is_bcbs_payer] BIT NULL,
    [is_non_medicare_government_payer] BIT NULL,
    [active] BIT NULL,
    [firm_global_id] VARCHAR(100) NULL
);
GO
