CREATE TABLE [stg].[PayrollADP] (
    [PayrollADPID] INT IDENTITY(1,1) NOT NULL,
    [GroupName] NVARCHAR(100) NULL,
    [EmployeeName] NVARCHAR(255) NULL,
    [EmpID] INT NULL,
    [DeptNumber] NVARCHAR(50) NULL,
    [DeptWorked] NVARCHAR(50) NULL,
    [CostNumber] NVARCHAR(50) NULL,
    [CostWorked] NVARCHAR(50) NULL,
    [PayElement] NVARCHAR(100) NULL,
    [AccountName] NVARCHAR(100) NULL,
    [AccountNumber] NVARCHAR(180) NULL,
    [Amount] DECIMAL(18,2) NULL,
    [Debit] DECIMAL(18,2) NULL,
    [Credit] DECIMAL(18,2) NULL,
    [GLAccount] NVARCHAR(180) NULL,
    [CAT] NVARCHAR(50) NULL,
    [Main] NVARCHAR(10) NULL,
    [Type] NVARCHAR(10) NULL,
    [Loc] NVARCHAR(10) NULL,
    [Doc] NVARCHAR(10) NULL,
    [Other] NVARCHAR(10) NULL,
    [Test1] INT NULL,
    [Test2] INT NULL,
    [ADP] NVARCHAR(100) NULL,
    [LaborDist] NVARCHAR(50) NULL,
    [Roster] NVARCHAR(50) NULL,
    [Proof] NVARCHAR(100) NULL,
    [Benefits] NVARCHAR(100) NULL,
    [Notes] NVARCHAR(250) NULL,
    [DataSourceID] INT NULL,
    [LoadDatetime] DATETIME NULL DEFAULT (getdate()),
    CONSTRAINT [PK__PayrollA__176557546182AA63] PRIMARY KEY ([PayrollADPID])
);
GO
